### PR TITLE
Fcal pi0 Igal plugin for calibration

### PR DESCRIPTION
**Pull request by subrahmakondi**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^FCAL_Pi0/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^FCAL_Pi0/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^FCAL_Pi0/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^FCAL_Pi0/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^FCAL_Pi0/make_FCAL_Pi0.log](https://halldweb.jlab.org/pull_request_test/halld_recon^FCAL_Pi0/make_FCAL_Pi0.log)
 Build report: [/work/halld/pull_request_test/halld_recon^FCAL_Pi0/report_FCAL_Pi0.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^FCAL_Pi0/report_FCAL_Pi0.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^FCAL_Pi0

**Comment by markito3** [comment]
Anyone want to take a peek at this one?

**Comment by sdobbs** [comment]
The filling of the histograms in imgg is not thread-safe.  Please either put in the appropriate locks or use the FillNDHistogram() functions.  Also, 2800 histograms with 7000 bins each... that's a lot of memory.

Also, the SContruct file in the plugin directory should be changed to an SConscript file, like similar plugins in this directory.

**Comment by subrahmakondi** [comment]
Dear All,
Thanks for the suggestions.
I will definitely modify the script.
Regards
Chandra

**Comment by sdobbs** [comment]
are we still considering to merge this plugin?
if not, we should close this pull request

**Comment by subrahmakondi** [comment]
Hello All,
Please close this pull request.
Thanks,
Chandra

**Comment by sdobbs** [comment]
Closed at author's request

**Pull request closed without merging**
