### PR TITLE
Clean up CDC afterpulses

### PR DESCRIPTION
**Pull request by nsjarvis**
This removes small afterpulses from CDC hits found on the same HVB and shortly after a saturated pulse.  It is on by default, can be switched off using -PCDC:ECHO_OPT=0.

I put this new code into DCDCHit_factory_calib and removed Beni's old code from DCDCHit_factory.  
However, if we ever want to use this to remove simulated afterpulses then it'll have to be moved into Hit_factory and modified to work with the HDDM data (without digihits).  Beni's trick for doing that is moved into the afterpulse identification function for future reference and commented out.   At present there aren't any afterpulses in the simulated data.

I added a Utilities plugin cdc_echo for identifying afterpulses, it creates a tree of pulse data and the boolean hitpresent, set true if a pulse survives to become a hit. 

Also I tidied up some misaligned tabs in libraries/DAQ/JEventSource_EVIOpp.cc to remove a paragraph of compiler warnings.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Comment by nsjarvis** [comment]
Will it automatically try to build itself again?  It was failing on the plugin, variable-sized arrays cannot be initialized.  I just fixed that.

**Comment by sdobbs** [comment]
yes, an automated build starts again every time you push new changes to the branch

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Comment by aaust** [comment]
The test fails when you push changes while another test is running. I will resubmit it once you are done.

**Comment by nsjarvis** [comment]
Thank you

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/make_nsj_cdc_cleanup.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_cleanup/report_nsj_cdc_cleanup.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_cleanup

**Review by zihlmann — APPROVED** [review]

**Pull request merged**
