### PR TITLE
Dirc commissioning 2019

### PR DESCRIPTION
**Pull request by jrstevenjlab**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_commissioning_2019

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_commissioning_2019

**Comment by jrstevenjlab** [comment]
Is the autobuild not working or did it really fail?  The failed message comes almost instantly after I pushed the updated commits.

**Comment by markito3** [comment]
The build was failing because it could not clone the halld_recon repository. There was a log-like file in the way. I have not seen this before. Cleared out all files associated with this pull request, re-submitted the test, and the build is proceeding now.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_commissioning_2019

**Pull request merged**
