### PR TITLE
Kin fitter debug v2

### PR DESCRIPTION
**Pull request by lihaoahil**
Added new tolerance tuning routine to fix issue #39 while avoiding crash.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^kinFitter_debug_v2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^kinFitter_debug_v2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^kinFitter_debug_v2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^kinFitter_debug_v2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^kinFitter_debug_v2/make_kinFitter_debug_v2.log](https://halldweb.jlab.org/pull_request_test/halld_recon^kinFitter_debug_v2/make_kinFitter_debug_v2.log)
 Build report: [/work/halld/pull_request_test/halld_recon^kinFitter_debug_v2/report_kinFitter_debug_v2.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^kinFitter_debug_v2/report_kinFitter_debug_v2.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^kinFitter_debug_v2

**Comment by markito3** [comment]
Have Hao's improvements ever been on the master branch? If not, are we ready to start using them in production?

marki@jlab.org, (757)269-5295

________________________________

**Comment by sdobbs** [comment]
They have not been on the master, but Alex and others have performed extensive tests.

The more relevant question is if we want to use them for the analysis launch over the 2018 data.

On Thu, Apr 4, 2019 at 9:12 AM Mark M. Ito <notifications@github.com<mailto:notifications@github.com>> wrote:
Have Hao's improvements ever been on the master branch? If not, are we ready to start using them in production?

marki@jlab.org<mailto:marki@jlab.org>, (757)269-5295

________________________________

**Comment by aaust** [comment]
>  The more relevant question is if we want to use them for the analysis launch over the 2018 data.

Yes, we want to use them. Without these changes, it does not make much sense to look at the baryon-antibaryon channels.

**Pull request merged**
