### PR TITLE
Add additional error checks and optional hardcoded configuration valu…

### PR DESCRIPTION
**Pull request by sdobbs**
…es for when those BOR's just don't show up.e

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/make_sdobbs_f250emu_dec2019.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/make_sdobbs_f250emu_dec2019.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/report_sdobbs_f250emu_dec2019.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f250emu_dec2019/report_sdobbs_f250emu_dec2019.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_f250emu_dec2019

**Comment by jrstevenjlab** [comment]
Do you want USE_CRATE_DEFAULTS = 1 as the default, or should it be 0 by default and users can set it on the command line if needed?

**Comment by sdobbs** [comment]
I think it should be on by default - these are the values that are generally in the BORs and are only used when the BORs are not available.  We've never run such that the same configuration parameters are set for every single f250.

**Comment by jrstevenjlab** [comment]
Sounds good

**Pull request merged**
