### PR TITLE
Monitoring plugin for fa125 including the FMWPC fadcs in roc 80

### PR DESCRIPTION
**Pull request by nsjarvis**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/make_nsj_cpp_itrig.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/make_nsj_cpp_itrig.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/report_nsj_cpp_itrig.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/report_nsj_cpp_itrig.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cpp_itrig

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/make_nsj_cpp_itrig.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/make_nsj_cpp_itrig.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/report_nsj_cpp_itrig.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/report_nsj_cpp_itrig.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cpp_itrig

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/make_nsj_cpp_itrig.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/make_nsj_cpp_itrig.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cpp_itrig/report_nsj_cpp_itrig.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cpp_itrig/report_nsj_cpp_itrig.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cpp_itrig

**Review by aaust — APPROVED** [review]
Looks reasonable. The previous test failed due to a problem with the nightly build.

**Pull request merged**
