### PR TITLE
add DIRC LED skims

### PR DESCRIPTION
**Pull request by sdobbs**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim/make_sdobbs_dirc_led_skim.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_dirc_led_skim/make_sdobbs_dirc_led_skim.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim/report_sdobbs_dirc_led_skim.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_dirc_led_skim/report_sdobbs_dirc_led_skim.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim

**Comment by sdobbs** [comment]
Is there a problem with the build environment?

ROOTSYS not defined or points to a non-existant directory!
make: *** [/w/halld-scifs17exp/pull_request_test/halld_recon^sdobbs_dirc_led_skim/.sconstruct_done] Error 255

**Comment by markito3** [comment]
I had an error in the cron job that changed the default version. I will 
try this test again...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_dirc_led_skim/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_dirc_led_skim/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim/make_sdobbs_dirc_led_skim.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_dirc_led_skim/make_sdobbs_dirc_led_skim.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim/report_sdobbs_dirc_led_skim.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_dirc_led_skim/report_sdobbs_dirc_led_skim.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_dirc_led_skim

**Pull request merged**
