### PR TITLE
* add new definitions for nuclear ions in particleType.h [rtj]

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by sdobbs** [comment]
Richard,
Thanks this is great, but if you change the numbering for existing particles, it breaks the analysis of files which have already been generated and some other coordinated changes with event generators need to take place, so I would prefer to avoid that if possible.

**Comment by rjones30** [comment]
Those charm particles (old codes 82-94) were misassigned. Those codes are already defined to be heavy ions in geant3. The numbers are hard-coded in g3. Their assignment to charm particles was misleading us to thinking that they are actually this type. This change just manifests what was true all along for those codes. In hdgeant4, they were not supported types until now.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/make_new_particle_types_for_nuclei_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/make_new_particle_types_for_nuclei_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/report_new_particle_types_for_nuclei_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj/report_new_particle_types_for_nuclei_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^new_particle_types_for_nuclei_rtj

**Comment by sdobbs** [comment]
OK, thanks for clarifying this, let's move ahead in this direction then - I'll go through halld_sim and make any required modifications.

**Pull request merged**
