### PR TITLE
Many DIRC changes to correctly add North OB to monitoring and several analysis updates

### PR DESCRIPTION
**Pull request by jrstevenjlab**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/make_dirc_tree_fix.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/make_dirc_tree_fix.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/report_dirc_tree_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/report_dirc_tree_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_tree_fix

**Comment by sdobbs** [comment]
tests are timing out, Mark is looking into this

On Tue, Oct 22, 2019 at 3:49 PM gluex <notifications@github.com<mailto:notifications@github.com>> wrote:

Test status for this pull request: FAILURE

Failures: /work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/failures.txt<https://halldweb.jlab.org/pull_request_test/halld_recon%5Edirc_tree_fix/tests-failures.txt>
Summary: /work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/summary.txt<https://halldweb.jlab.org/pull_request_test/halld_recon%5Edirc_tree_fix/tests-summary.txt>
Logs: /work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/log<https://halldweb.jlab.org/pull_request_test/halld_recon%5Edirc_tree_fix/tests-logs>

Build log: /work/halld/pull_request_test/halld_recon^dirc_tree_fix/make_dirc_tree_fix.log<https://halldweb.jlab.org/pull_request_test/halld_recon%5Edirc_tree_fix/make_dirc_tree_fix.log>
Build report: /work/halld/pull_request_test/halld_recon^dirc_tree_fix/report_dirc_tree_fix.txt<https://halldweb.jlab.org/pull_request_test/halld_recon%5Edirc_tree_fix/report_dirc_tree_fix.txt>
Location of build: /work/halld/pull_request_test/halld_recon^dirc_tree_fix

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/make_dirc_tree_fix.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/make_dirc_tree_fix.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_tree_fix/report_dirc_tree_fix.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_tree_fix/report_dirc_tree_fix.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_tree_fix

**Comment by jrstevenjlab** [comment]
bump

**Pull request merged**
