### PR TITLE
Plugin used to read LED data from LED skims. Code to do 4ns correctio…

### PR DESCRIPTION
**Pull request by gleasonc**
…ns also included.

### CODE REVIEW

**Comment by sdobbs** [comment]
@gleasonc for the plugin, can you remove the SConstruct and replace it with a standard SConscript, similar to the other plugins in this directory?

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/make_FCALLEDTree.log](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/make_FCALLEDTree.log)
 Build report: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/report_FCALLEDTree.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/report_FCALLEDTree.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^FCALLEDTree

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/make_FCALLEDTree.log](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/make_FCALLEDTree.log)
 Build report: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/report_FCALLEDTree.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/report_FCALLEDTree.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^FCALLEDTree

**Comment by gleasonc** [comment]
Someone with more experience might need to tell me why this failed. It built fine for me on the ifarm.

**Comment by sdobbs** [comment]
I think something got interrupted... clearing the test and restarting...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/make_FCALLEDTree.log](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/make_FCALLEDTree.log)
 Build report: [/work/halld/pull_request_test/halld_recon^FCALLEDTree/report_FCALLEDTree.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^FCALLEDTree/report_FCALLEDTree.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^FCALLEDTree

**Pull request merged**
