### PR TITLE
Correct bug in time calc TMath::C() is m/s unit needs to be m/ns

### PR DESCRIPTION
**Pull request by igjaegle**
Correct bug found by Drew in the time calculation i.e. use proper unit for TMath::C() m/s -> m/ns

### CODE REVIEW

**Comment by andrsmit** [comment]
I believe you should use cm/ns rather than m/ns, since the shower positions are given in cm.

**Comment by igjaegle** [comment]
Done.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle_skims

**Comment by andrsmit** [comment]
Sorry, I think you should multiply by a factor of 1e7 instead of 1e6. Right?

**Comment by igjaegle** [comment]
yes you are right of course.

**Comment by igjaegle** [comment]
Yes you are right of course. The correction is done.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle_skims

**Pull request merged**
