### PR TITLE
change to the comment in the README

### PR DESCRIPTION
**Pull request by markito3**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pull_request_test

**Comment by markito3** [comment]
Going to roll back build_scripts one version and see if that helps...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pull_request_test

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pull_request_test

**Comment by rjones30** [comment]
Not sure what the "Build status for this pull request: FAILURE" means in this case, going ahead anyway!
-Richard

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pull_request_test

**Comment by markito3** [comment]
This pull request was meant as a test of the pull-request-test webhook 
(automatic build and test) and does not represent a real change to the 
code. No harm merging it, and there would have been no harm if it had 
never been merged. There are multiple failures here; @sdobbs and I were 
trying to restore some of the tests that actually ran the built binaries.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pull_request_test

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/make_test_pull_request_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pull_request_test/report_test_pull_request_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pull_request_test

**Pull request merged**
