### PR TITLE
Fix to look at trigger energy sums with EVIO data

### PR DESCRIPTION
**Pull request by sdobbs**
This is likely a temporary solution for current trigger studies until we implement a better solution.
Prevents excess of error messages being printed to the screen.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/make_sdobbs_trigger_updates.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/make_sdobbs_trigger_updates.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/report_sdobbs_trigger_updates.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/report_sdobbs_trigger_updates.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates

**Comment by sdobbs** [comment]
Also added a change to the monitoring histograms to give a better determination of the trigger efficiency in MC.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/make_sdobbs_trigger_updates.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/make_sdobbs_trigger_updates.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates/report_sdobbs_trigger_updates.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_trigger_updates/report_sdobbs_trigger_updates.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_trigger_updates

**Comment by sdobbs** [comment]
bump

**Pull request merged**
