### PR TITLE
hdview2 Skip events and CTOF

### PR DESCRIPTION
**Pull request by faustus123**
This implements a new feature to allow hdview2 to automatically skip events not containing some desired objects. IT is terribly fast, but much faster than clicking through manually.

This also includes some visualization of the CTOF for CPP/NPP

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/make_davidl_hdview2.log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/make_davidl_hdview2.log)
 Build report: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/report_davidl_hdview2.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/report_davidl_hdview2.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^davidl_hdview2

**Comment by aaust** [comment]
It looks like it is skipping all event if no -D option is given. I suggest keeping the original behavior whenever no object is specified.

**Comment by faustus123** [comment]
Fixed bug Alex noted. Can be tried again.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/make_davidl_hdview2.log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/make_davidl_hdview2.log)
 Build report: [/work/halld/pull_request_test/halld_recon^davidl_hdview2/report_davidl_hdview2.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hdview2/report_davidl_hdview2.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^davidl_hdview2

**Review by aaust — APPROVED** [review]
It works, thank you!

**Pull request merged**
