### PR TITLE
Hddm with hdf5 support rtj

### PR DESCRIPTION
**Pull request by rjones30**
This merges a new feature branch into Master, bringing in support for hddm i/o to HDF5 formatted files. HDF5 is a standard for publication and archival of scientific data in the public domain. HDF5 i/o options are not currently available in the hdgeant4 master branch, nor is it yet supported by the master branches of DEventSourceHDDM jana event source used by mcsmear or hd_root to read MonteCarlo data. HDF5 options will be introduced in new feature branches for each of these applications  in the near future, as well as the REST data writers and readers,. But before that can happen, the basic HDF5 capability within the hddm libraries needs to be present in Master, and interested people should have a chance to play with it.

Merging this PR will not produce any immediate changes to the behavior of applications because enabling of HDF5 support in hddm depends on a new environment variable HDF5ROOT being defined in the build scripts, pointing to the local install of the HDF5 library. This PR does not assume that HDF5 has already been installed. As soon as users wanting to experiment with this new capability install a local copy of the HDF5 package and add HDF5ROOT to their local setup script and rebuild halld_recon, they will get the new HDF5 support automatically enabled in the hddm library, and be able to experiment with the new ability of the hddm python module and/or C++ i/o classes to translate between HDF5 and native hddm stream formats, and try out their favorite tools for browsing and manipulating HDF5 formatted data.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/make_hddm_with_hdf5_support_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/make_hddm_with_hdf5_support_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/report_hddm_with_hdf5_support_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj/report_hddm_with_hdf5_support_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^hddm_with_hdf5_support_rtj

**Review by markito3 — COMMENTED** [review]
looks good

**Review by markito3 — APPROVED** [review]
approving

**Comment by markito3** [comment]
Richard,

1) I have been working on having scons files that interoperate between python 2 and python 3, e.g., no more sbms.py and sbms3.py, just one sbms.py that works for both. I submitted a pull request using this scheme yesterday.
2) I merged in this hdf5 pull request yesterday when my pull request was still outstanding. So you made it onto the master branch first.
3) The hdf5 changes rendered my branch _not_ automatically merge-able. Easy to see why. sbms.py was significantly different between the two branches and sbms3.py is missing from my branch since on my branch sbms.py pulls double duty.
4) I then had to merge your changes, now on the master, onto my branch by hand. Which is how things are supposed to work. The goal is to have hdf5 support appear in the single sbms.py on my branch.
5) My pull request has not been merged at this writing.
6) You may have to look critically at how the merge was done. I think I got it right, but have no way to test it. Since it does not effect things in the default build, the building part should go forward for now without a problem.

  -- Mark

**Pull request merged**
