### PR TITLE
Ccal recon

### PR DESCRIPTION
**Pull request by somovalex**
Initial implementation of the island CCAL clustering algorithm (provided by I.Larin)

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ccal_recon

**Comment by staylorjlab** [comment]
I was able to recompile and run hdview2 after checking this out, even though the automated build test failed -- merge in spite of build test failure?  Can someone restart the build test?

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ccal_recon

**Comment by staylorjlab** [comment]
Okay, I'll wait.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ccal_recon

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/make_ccal_recon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_recon/report_ccal_recon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ccal_recon

**Comment by sdobbs** [comment]
yeah, I don't understand why the test is pulling a bad version of hdview2...

I have added the CCDB changes we talked about, at least.

**Pull request closed without merging**
