### PR TITLE
Add code to mask dead channels when reading in HDDM/REST events

### PR DESCRIPTION
**Pull request by sdobbs**
This is mainly for random hits that are merged in, when the bad channel mask was updated after the random trigger files were created

Addresses issue #810

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/make_sdobbs_tagger_dead_channels.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/make_sdobbs_tagger_dead_channels.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/report_sdobbs_tagger_dead_channels.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_tagger_dead_channels/report_sdobbs_tagger_dead_channels.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_tagger_dead_channels

**Comment by jrstevenjlab** [comment]
@lihaoahil, could you confirm this addresses one of the issues you've observed in the energy dependence of the reconstruction efficiency?  

And is my understanding correct that this will need to be ported to the recon compatible analysis versions for previous run periods?

**Review by lihaoahil — APPROVED** [review]
This new feature has been tested successfully after rebased to 4.51.0 (for detail see [here](https://github.com/JeffersonLab/halld_recon/issues/810#issuecomment-2398155366)).

**Comment by lihaoahil** [comment]
@sdobbs I believe this is need to be ported to the Recon-launch-compatible versions for previous run periods to get more accurate reconstruction efficiency?

**Comment by sdobbs** [comment]
yes, but I didn't want to start the work until it was merged with the main branch.  putting this on my list

**Pull request merged**
