### PR TITLE
Properly set TAGH energy based on current geometry

### PR DESCRIPTION
**Pull request by sdobbs**
Should fix issue #763

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/make_sdobbs_rest_tagger_fix_nov2023.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/make_sdobbs_rest_tagger_fix_nov2023.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/report_sdobbs_rest_tagger_fix_nov2023.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/report_sdobbs_rest_tagger_fix_nov2023.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023

**Review by staylorjlab — COMMENTED** [review]
The continues on lines 654 and 715 lead to memory leaks if they are called.  The DBeamPhoton* gamma = new DBeamPhoton();
lines should be moved after these lines.

**Comment by sdobbs** [comment]
Thanks for the catch, Simon - that should be fixed now.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/make_sdobbs_rest_tagger_fix_nov2023.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/make_sdobbs_rest_tagger_fix_nov2023.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/report_sdobbs_rest_tagger_fix_nov2023.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023/report_sdobbs_rest_tagger_fix_nov2023.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_fix_nov2023

**Review by aaust — APPROVED** [review]
looks reasonable

**Pull request merged**
