### PR TITLE
Helicity tools

### PR DESCRIPTION
**Pull request by kliv**
plugin to get helicity information from 2023 data in the form of log file. 
scripts to make lookup tables and plots from the log file.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^helicity_tools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^helicity_tools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^helicity_tools/make_helicity_tools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/make_helicity_tools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^helicity_tools/report_helicity_tools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/report_helicity_tools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^helicity_tools

**Comment by jrstevenjlab** [comment]
FYI, the helicity bits are now in the CCDB translation table https://logbooks.jlab.org/entry/4267055, so these helicity tools should work without requiring a private (tt.xml) version of the translation table as they had previously.

**Comment by aaust** [comment]
@jrstevenjlab @kliv What else is needed to merge these tools?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^helicity_tools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^helicity_tools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^helicity_tools/make_helicity_tools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/make_helicity_tools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^helicity_tools/report_helicity_tools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^helicity_tools/report_helicity_tools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^helicity_tools

**Review by jrstevenjlab — APPROVED** [review]
Functional helicity retrieval from data stream.  This still requires some external configuration/setup files for the plugin included in this PR.  For data production, likely prefer these inputs to be included in CCDB

**Pull request merged**
