### PR TITLE
Peedestal noise plugin improvements

### PR DESCRIPTION
**Pull request by markdalton**
Added new histograms (windowSigma) which give the collection of sigmas from each window for each channel.  These are Gaussian distributed.  The mean and error from theses histograms are what should be used for the noise in each channel.  Added a debug flag which shows some more calculation details for a single channel.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^dalton_pedestalnoise/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dalton_pedestalnoise/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^dalton_pedestalnoise/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^dalton_pedestalnoise/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^dalton_pedestalnoise/make_dalton_pedestalnoise.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dalton_pedestalnoise/make_dalton_pedestalnoise.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dalton_pedestalnoise/report_dalton_pedestalnoise.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dalton_pedestalnoise/report_dalton_pedestalnoise.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dalton_pedestalnoise

**Comment by sdobbs** [comment]
Are we waiting on Varun's checks to merge this?

**Comment by markdalton** [comment]
I think Varun is using the new features successfully and this can be merged.

**Comment by varunneelamana** [comment]
Yes, I am using it successfully and it can be merged. Sorry, I didn't know whether it required more approval or I am allowed to merge it.

**Comment by markdalton** [comment]
Anyone can merge as long as you are confident that it works.  For a plugin the stakes are lower than for a library etc.  Since you've actually tested it you've done more than most reviewers will do.

**Comment by varunneelamana** [comment]
Thanks Mark. I got it.

**Pull request merged**
