### PR TITLE
Latest PrimEX FCAL calibration skimmer & analyzer

### PR DESCRIPTION
**Pull request by igjaegle**
The latest and most up-to-date FCAL calibration skimmer & analyzer are added. I will use these versions for LH2 cal. w/  CCAL

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log)
 Build report: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^primex-fcal-cal

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log)
 Build report: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^primex-fcal-cal

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log)
 Build report: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^primex-fcal-cal

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log)
 Build report: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^primex-fcal-cal

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log)
 Build report: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^primex-fcal-cal

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/make_primex-fcal-cal.log)
 Build report: [/work/halld/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex-fcal-cal/report_primex-fcal-cal.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^primex-fcal-cal

**Comment by igjaegle** [comment]
I updated the FCAL cal analyzer and added some macro to make nice plots

**Comment by igjaegle** [comment]
@andrsmit & @somovalex , this is the most up-to-date FCAL calibration plugins and FCAL pi0 skimmer + macro

**Comment by somovalex** [comment]
Looks Ok, may need to check more

**Review by somovalex — APPROVED** [review]
Looks Ok, need to check more

**Pull request merged**
