### PR TITLE
added Df125TriggerTime info

### PR DESCRIPTION
**Pull request by nsjarvis**

### CODE REVIEW

**Comment by nsjarvis** [comment]
I forgot something important.  Will add it.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/make_nsj_cdc_scan_ext.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/make_nsj_cdc_scan_ext.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/report_nsj_cdc_scan_ext.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/report_nsj_cdc_scan_ext.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/make_nsj_cdc_scan_ext.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/make_nsj_cdc_scan_ext.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext/report_nsj_cdc_scan_ext.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_scan_ext/report_nsj_cdc_scan_ext.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_scan_ext

**Comment by nsjarvis** [comment]
Please merge this, someone.  
@zihlmann  this is the plugin that makes trees of Df125 rocid slot channel & pulse info, I added a triggertime tree.

**Review by zihlmann — APPROVED** [review]

**Pull request merged**
