### PR TITLE
Pasteurize rebased mmi

### PR DESCRIPTION
**Pull request by markito3**
Uses pasteurized versions of SCons files.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log)
 Build report: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log)
 Build report: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log)
 Build report: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log)
 Build report: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log)
 Build report: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log)
 Build report: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/make_pasteurize_rebased_mmi.log)
 Build report: [/work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^pasteurize_rebased_mmi/report_pasteurize_rebased_mmi.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^pasteurize_rebased_mmi

**Comment by markito3** [comment]
bump...

**Review by sdobbs — APPROVED** [review]
looks fine

**Pull request merged**
