### PR TITLE
Added rho-minus photoproduction reconstruction plugin for SRC-CT analysis

### PR DESCRIPTION
**Pull request by JacksonPybus**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log)
 Build report: [/work/halld/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^src-ct-dev

**Comment by sdobbs** [comment]
Same comment as on #566 - I expect that this will crash and burn in our normal monitoring environment unless you use DTreeInterface to write out the trees, since this is horribly thread-unsafe.

The global histogram variables could either be made static or members of the JEventProcessor class

**Comment by aaust** [comment]
I tested the plugin, and did not see any crashes in neither single- nor multi-threaded mode. The processing rate approximately scales with the number of threads.

Currently, the tree is saved into the histogram file, which would make it unnecessarily heavy. I will try to have a modified version which uses the DTreeInterface and writes out a separate tree by tomorrow.

**Comment by aaust** [comment]
Restructured SRC plugin:
* moved histograms to folder 'SRC_1p1pi1pi0'
* usedDTreeInterface to safely write tree to file 'tree_1p1pi1pi0.root'
* avoided all global variables
* corrected compiler warnings

The tree has almost the same structure as yours, only the fixed arrays for the showers were split into 2 individual elements. I tested it on raw and rest data files, but not on MC. Please verify that all entries make sense.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log)
 Build report: [/work/halld/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^src-ct-dev

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log)
 Build report: [/work/halld/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^src-ct-dev

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log)
 Build report: [/work/halld/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^src-ct-dev

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^src-ct-dev/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/make_src-ct-dev.log)
 Build report: [/work/halld/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src-ct-dev/report_src-ct-dev.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^src-ct-dev

**Comment by markito3** [comment]
The nightly build was incomplete at the time of the test, thus the initial failure. I re-submitted the test.

**Review by aaust — APPROVED** [review]
Tested the plugin on a small data sample and the results look fine. I merge it to include it in the offline monitoring system, which will allow for more thorough testing.

**Pull request merged**
