### PR TITLE
TOF energy calibration features

### PR DESCRIPTION
**Pull request by zihlmann**
This code change in DTOFPoint_factory adds two variables that contain the energy deposition of
the particle separately for the two planes: dE1 and dE2. the energies are attenuated to the
center of the paddle representing the unbiased un-attenuated energy deposited matched to
what is seen in the MC simulation.
In addition a small bug is fixed in dTOFPaddle_facotory

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^master/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^master/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^master/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^master/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^master/make_master.log](https://halldweb.jlab.org/pull_request_test/halld_recon^master/make_master.log)
 Build report: [/work/halld/pull_request_test/halld_recon^master/report_master.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^master/report_master.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^master

**Comment by sdobbs** [comment]
So I'm confused here, none of the changes listed in this PR seem to have anything to do with Beni's description?  They seem to all be from other PRs?

**Comment by aaust** [comment]
He wants to merge master into TOFEcalib, not the other way round.

**Comment by sdobbs** [comment]
Good point, no permission needed for that =)  Will close.

**Comment by zihlmann** [comment]
ok What it really looks like that gitub is just what it is, a pile of 
S~!~~~~

I will never ever use a branch again!
I want my code to be in the master, period! nothing else. But for the 
first time
trying to use a branch and did not go that well. F ..... it.
go back to the old ways.
I guess I have to start from scratch again.

**Comment by aaust** [comment]
This page has step-by-step instructions and very useful examples:
https://halldweb.jlab.org/wiki/index.php/Guide_to_Using_Git

**Pull request closed without merging**
