### PR TITLE
Modified the Monitoring/highlevel_online plugin 

### PR DESCRIPTION
**Pull request by varunneelamana**
Modified the Monitoring/highlevel_online plugin by including BCAL LED  pseudoTrigger and code for Triggerplots

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/make_Varun_FPtriggerplot.log](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/make_Varun_FPtriggerplot.log)
 Build report: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/report_Varun_FPtriggerplot.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/report_Varun_FPtriggerplot.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot

**Comment by zihlmann** [comment]
dHist_L1bits_fp_twelvehundhits->Fill(pseudo_triggerbit);
the histogram only ranges from 7.5 to 11.5 so:
if pseudo_triggerbit is zero, this happens if the LED trigger is not recognized by the front pannel but
the LED did fire and lots of BCAL modules provide data, it will end up in the underflow bin.

**Comment by zihlmann** [comment]
I see what you did and I have two comments
a) locdbcalhits.size() is unsigned int type so 1200 not 1200.
b) I would prefer to have the >1200 hits in a separate bin so that one can see how often such a 
situation can happen where the front panel bit is not set but the LED did fire.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/make_Varun_FPtriggerplot.log](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/make_Varun_FPtriggerplot.log)
 Build report: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/report_Varun_FPtriggerplot.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/report_Varun_FPtriggerplot.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot

**Comment by zihlmann** [comment]
Now  the logic is pretty much  broken particularly in the first part, 
let me show you how it should look like:

    int pseudo_triggerbit = 0;
    if(LED_US){
        pseudo_triggerbit = 8;
          	
        if (locdbcalhits.size() >1200){
            pseudo_triggerbit=9;
        }
     }
     
     if (LED_DS){
        pseudo_triggerbit=10

        if (locdbcalhits.size() >1200){
           pseudo_triggerbit=11;
        }
     }
     dHist_L1bits_fp_twelvehundhits->Fill(pseudo_triggerbit);

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/make_Varun_FPtriggerplot.log](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/make_Varun_FPtriggerplot.log)
 Build report: [/work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot/report_Varun_FPtriggerplot.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^Varun_FPtriggerplot/report_Varun_FPtriggerplot.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^Varun_FPtriggerplot

**Pull request merged**
