### PR TITLE
remove the word "simulation"

### PR DESCRIPTION
**Pull request by markito3**
minor change with no effect on functionality to test auto-build on pull request

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pr_test

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pr_test

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pr_test

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pr_test

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^test_pr_test/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^test_pr_test/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/make_test_pr_test.log)
 Build report: [/work/halld/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^test_pr_test/report_test_pr_test.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^test_pr_test

**Comment by sdobbs** [comment]
are we keeping this open?

**Comment by markito3** [comment]
no substantive changes, closing without merging

**Pull request closed without merging**
