### PR TITLE
Tpol sector

### PR DESCRIPTION
**Pull request by SebsMedDr**
Updates to TPOL digihit, TPOL tree, and online monitoring of TPOL. This allows for determination of sector by translation table, as well as obtain the waveform from the TPOL digihit object. The online monitoring plugin was also updated to include new occupancy plots to suppress noisy channels. The RF and TPOL occupancy macro was updated to create a canvas with the three TPOL occupancy plots.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tpol_sector

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tpol_sector

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^tpol_sector/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^tpol_sector/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tpol_sector

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^tpol_sector/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^tpol_sector/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/make_tpol_sector.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tpol_sector/report_tpol_sector.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tpol_sector

**Comment by jrstevenjlab** [comment]
The TPOLHit factory hasn't been updated for the newest DigiHit code.  So this code won't produce DTPOLHit objects...

**Comment by jrstevenjlab** [comment]
Nevermind, ignore my previous comment.  I missed the final pushes which fixed this issue

**Pull request merged**
