### PR TITLE
Implement suggested calorimeter fiducial cuts at analysis level

### PR DESCRIPTION
**Pull request by sdobbs**
Implement the cuts suggested by Mark Dalton's studies:
- reject showers in the FCAL/BCAL transition region by cutting on BCAL z and FCAL R
- reject showers near the beampipe by making a list of crystals and rejecting showers who have a center inside of them

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/make_sdobbs_cal_fiducial_cuts.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/make_sdobbs_cal_fiducial_cuts.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/report_sdobbs_cal_fiducial_cuts.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts/report_sdobbs_cal_fiducial_cuts.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_cal_fiducial_cuts

**Comment by aaust** [comment]
Can we please wait until we have a recon test with pull request #184 ? I would like to see the effects independently.

**Comment by sdobbs** [comment]
Sounds good to me - we should hold off on merging then.

**Comment by aaust** [comment]
The recon test from 2019-08-01 shows the status before this pull request.

**Pull request merged**
