### PR TITLE
Add PRIMEXD skimmer

### PR DESCRIPTION
**Pull request by igjaegle**
Add different skimmers for PRIMEXD
1/ eta2g_primexd_skim -> eta Primakoff in FCAL, evio reduced by 4400
2/ eta6g_primexd_skim -> eta ->3pi0 and etaprime ->2pi0 eta, evio reduced by 575
3/ etapi0_primed_skim -> etapi0/etaeta/pi0pi0 skims, evio reduced by 8
4/ compton "neutral" skim, evio reduced by 36
5/ single "neutral" skim, evio reduced by 12

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle_skims

**Comment by sdobbs** [comment]
These look good, though for the eta EVIO skims, why not just save the full event, rather than building a large, non-comprehensive list of the objects to save?

**Comment by igjaegle** [comment]
I did not find how to do that yet, is there an example for this?

**Comment by somovalex** [comment]
We need to write the whole event, similar to other skims

________________________________

**Comment by sdobbs** [comment]
Most other EVIO skims don't write the whole event, which is why they are so
small.


But I agree that analysis oriented skims should write out the full events.

**Comment by igjaegle** [comment]
ok thanks, I will do the correction

**Comment by igjaegle** [comment]
The entire event is now saved for all skims. Each skim size increases roughly by a factor 2.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle_skims

**Pull request merged**
