### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by subrahmakondi**
Invariant mass of 2 gamma histogram fits for different FCAL regions

### CODE REVIEW

**Comment by subrahmakondi** [comment]
Invariant mass of 2 gamma histogram fits for different FCAL regions

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^chandra_calib/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^chandra_calib/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^chandra_calib/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^chandra_calib/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^chandra_calib/make_chandra_calib.log](https://halldweb.jlab.org/pull_request_test/halld_recon^chandra_calib/make_chandra_calib.log)
 Build report: [/work/halld/pull_request_test/halld_recon^chandra_calib/report_chandra_calib.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^chandra_calib/report_chandra_calib.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^chandra_calib

**Comment by jrstevenjlab** [comment]
Hi Chandra,

We don't typically put scripts like this in the base directory of halld_recon.  Do these go with a particular plugin that you could include them in that plugin's directory?  If not, the [hd_utilities](https://github.com/JeffersonLab/hd_utilities) repository may be a better place to keep these calibration scripts.

-Justin

**Comment by subrahmakondi** [comment]
Dear Dr.  Justin,
I will remove from here and put in hd_utilities   separately tomorrow.
Sorry for the inconvenience.
Thanks for your valuable suggestion.
With regards,
Chandra

**Comment by jonzarling** [comment]
Hi Chandra, it appears these files still appear in the base directory of halld_recon. Could you take another look at moving/removing them?

**Comment by subrahmakondi** [comment]
Hello Zarling,
I removed the files from Halld_recon.
Thanks for your time and cooperation.
With regards,
Chandra

**Comment by markdalton** [comment]
Another thing that wasn't mentioned here is that a pull request should be merged by someone other than the author.  This procedure acts as a first line of defense for the shared code. In future, please wait for someone else to merge your pull requests.  Please also never commit directly to the master.  This is even worse than merging your own pull request because it doesn't even allow the compilation test to complete first.

**Pull request merged**
