### PR TITLE
Fix various ROOT bugs in plugins

### PR DESCRIPTION
**Pull request by sdobbs**
Mostly some bad lock and directory behavior.  Most of these were identified by David Lawrence.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/make_sdobbs_pluginfix_aug2020_v2.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/make_sdobbs_pluginfix_aug2020_v2.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/report_sdobbs_pluginfix_aug2020_v2.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/report_sdobbs_pluginfix_aug2020_v2.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2

**Comment by sdobbs** [comment]
bump

**Comment by aaust** [comment]
I would prefer to remove the lines that are no longer needed instead of having commented out lines in the code without explanation.

**Comment by sdobbs** [comment]
I think I cleaned up the lines you were referring to.  There's a few more changes I'd consider going back to improve, but I'm hoping to get these changes in since they also affect the calibration jobs.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/make_sdobbs_pluginfix_aug2020_v2.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/make_sdobbs_pluginfix_aug2020_v2.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/report_sdobbs_pluginfix_aug2020_v2.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2/report_sdobbs_pluginfix_aug2020_v2.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_pluginfix_aug2020_v2

**Pull request merged**
