### PR TITLE
CPP angle hists and e/pi classifiers

### PR DESCRIPTION
**Pull request by acschick**
Added the e/pi TMVA classifier to the DCPPEpEm_factory.
Added angular histograms to the FMWPC_Performance plugin.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^CPPangleHists/make_CPPangleHists.log](https://halldweb.jlab.org/pull_request_test/halld_recon^CPPangleHists/make_CPPangleHists.log)
 Build report: [/work/halld/pull_request_test/halld_recon^CPPangleHists/report_CPPangleHists.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^CPPangleHists/report_CPPangleHists.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^CPPangleHists

**Comment by staylorjlab** [comment]
I have some idea how to fix this -- working on it now.

**Comment by staylorjlab** [comment]
Well, I thought I knew what is going on...

**Comment by staylorjlab** [comment]
I think this new code needs a fair amount of work:   there is quite a bit of duplicate code in the two new header files.  I am working on reorganizing a bit.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^CPPangleHists/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^CPPangleHists/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^CPPangleHists/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^CPPangleHists/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^CPPangleHists/make_CPPangleHists.log](https://halldweb.jlab.org/pull_request_test/halld_recon^CPPangleHists/make_CPPangleHists.log)
 Build report: [/work/halld/pull_request_test/halld_recon^CPPangleHists/report_CPPangleHists.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^CPPangleHists/report_CPPangleHists.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^CPPangleHists

**Pull request merged**
