### PR TITLE
Nsj cdc occupancy guidance

### PR DESCRIPTION
**Pull request by nsjarvis**
Beni, please could you check the call conditions?  Thanks!

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/make_nsj_cdc_occupancy_guidance.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/make_nsj_cdc_occupancy_guidance.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/report_nsj_cdc_occupancy_guidance.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance/report_nsj_cdc_occupancy_guidance.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_cdc_occupancy_guidance

**Comment by markdalton** [comment]
I think this is the wrong location.  Shouldn't it be here?

https://github.com/JeffersonLab/halld_recon/blob/master/src/plugins/monitoring/occupancy_online/CDC_occupancy.C

**Comment by markdalton** [comment]
Test

**Comment by nsjarvis** [comment]
I've no idea.   I didn't realise that there were 2 copies of this macro.
 Which one is running in the counting house?

**Comment by markdalton** [comment]
I'm 99% sure it's occupancy_online and not this one.

**Comment by aaust** [comment]
I can confirm, we use the one in occupancy_online

**Comment by nsjarvis** [comment]
OK I'll copy the stuff into that one.

**Pull request merged**
