### PR TITLE
Reverse forward fit

### PR DESCRIPTION
**Pull request by staylorjlab**
Implements a kalman filter in the reverse direction to the standard direction (from outer hits toward target) to find the best guess for the position and momentum at the exit of the tracking volume in the forward direction.   Optionally adds this data to the REST output.   Adds TRD drift time to track reconstruction if these hits are available.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReverseForwardFit

**Comment by sdobbs** [comment]
Just checking, is saving the track extrapolation at the end of the tracking volume enough to reswim the tracks if desired, i.e., the covariance matrix isn't needed?
Also, does this work for tracks which hit the BCAL as well?

**Comment by staylorjlab** [comment]
Right now the propagation of covariance matrix is not done for the extrapolations because none of the matching routines have hooks to use this information.    What I have added to the REST output should be enough to get the position and momentum at the DIRC/etc by doing the swimming through the field after the fact.
Also the new code adds the "exit" extrapolations if the forward version of the state vector is used even for angles greater than 10 degrees, so it should work for the BCAL as well.     I have not added the KalmanReverse algorithm for the more central tracks, but I can still add the extrapolation point using the existing information -- should I do this?
________________________________

**Comment by sdobbs** [comment]
I think it makes sense to add in the extrapolation point for the central values even if we don't use the KalmanReverse algorithm there, to leave the door open for future studies.

I'd be interested in at least the option to run KalmanReverse for the more central tracks, even if it isn't the default.  I am particularly thinking of situations like the protons in the J/psi analysis, where we have seen issues in track matching in the BCAL, so it would be nice to be able to study these in more detail further down the road.

**Comment by staylorjlab** [comment]
Okay, I will add the extrapolation point.    The KalmanReverse code is called for all tracks < 60 degrees, where the state vector changes.  I have not implemented the algorithm for theta>60 degrees.  I can do this, but the details are slightly different.

________________________________

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReverseForwardFit

**Comment by mashephe** [comment]
Sean,

On Apr 24, 2020, at 12:13 PM, Sean Dobbs <notifications@github.com<mailto:notifications@github.com>> wrote:

I'd be interested in at least the option to run KalmanReverse for the more central tracks, even if it isn't the default. I am particularly thinking of situations like the protons in the J/psi analysis, where we have seen issues in track matching in the BCAL, so it would be nice to be able to study these in more detail further down the road.

You'll have to go back to raw data to do this, right?  There is no option to run the Kalman filter without the hits in the chambers.

It would also be useful to evaluate the cost of the doing the swimming at analysis time with the information in REST file.  We  want to avoid potentially introducing a bottleneck at the analysis step, which I think probably currently dominated by kinematic fitting.

Matt

**Comment by sdobbs** [comment]
Matt,   Yes, we have skims of raw data for variations reactions like the
J/psi, for example.

**Comment by jrstevenjlab** [comment]
I did a couple quick checks over the data from run 71742.  Running interactively on the ifarm for 50k events, the REST files increase in size by ~18% and the processing event rate decreased by ~23%, neither of which seem intolerable for this monitoring launch, but we should see how it scales over more runs and larger numbers of jobs.   Matt is right that we need to determine the cost of re-doing the extrapolation at the analysis stage, but I don't think this should delay a merge of this PR.

Also, if we're going to use this in the impending monitoring launch, do we want to make the writing of exit parameters (REST_WRITE_TRACK_EXIT_PARAMS) true by default?  Right now it is not the default and for some reason when I try to set the command line parameter I get an error:

REST:WRITE_TRACK_EXIT_PARAMS = 1        <-- NO DEFAULT! (TYPO?)

Am I doing something wrong, or do the flags not work the same for the danarest plugin as others?

**Comment by staylorjlab** [comment]
Can someone do a quick check with the p2pi_hists plugin using this branch?  I am seeing some strange behavior.
________________________________

**Comment by staylorjlab** [comment]
I think I found the issue.   Fix coming soon.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReverseForwardFit

**Comment by jrstevenjlab** [comment]
After this push, looking at a small sample in p2pi_hists from run 71724 I see a ~5% lower rho yield without the kinematic fit and ~10% lower rho yield with the kinematic fit (both compared to the master).  

In both cases the lower yield seems to be due to the missing mass squared and kinematic fit confidence level cuts, respectively.  Prior to these cuts the number of candidate combos are basically the same as the master.  Its surprising to me that the MM^2 and KinFit cuts are affected by the new reverse kalman extrapolation, since I didn't think that made any changes to the 4-vector reported at the vertex used in the physics analysis.  

Simon, any thoughts why this might be the case?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReverseForwardFit

**Comment by staylorjlab** [comment]
I found what was causing the drop in yields -- it should be fixed with the most resent commits.   The KalmanReverse code was not the cause, although I did find some minor issues with that code as well.

**Comment by jrstevenjlab** [comment]
Thanks Simon.  Just confirming that I see the rho yields are back to their nominal levels as well.  My remaining question is do we want to set

REST_WRITE_TRACK_EXIT_PARAMS = true

by default?   This way we can test the extrapolation procedure when analyzing the REST files from monitoring launch.

-Justin

**Comment by staylorjlab** [comment]
Okay, I will change the default.

**Comment by sdobbs** [comment]
We could just set the flag to true on the monitoring launch, couldn't we?

**Comment by jrstevenjlab** [comment]
I tried setting the flag on the command line interactively, but got the error I mentioned previously

REST:WRITE_TRACK_EXIT_PARAMS = 1 <-- NO DEFAULT! (TYPO?)

I could just be doing something wrong, but it didn't look like the flag was getting setup properly this way.

**Comment by staylorjlab** [comment]
I saw that warning as well, but it looked like the extrapolation info was actually in the REST file.
________________________________

**Comment by zihlmann** [comment]
This should be the default, it is far too valuable information!

**Comment by sdobbs** [comment]
Right, if the data is in the REST file, then it's just a warning.  I don't remember how to properly solve this right now, but there's a similar pattern in several places in the code.

**Comment by staylorjlab** [comment]
Is the consensus to change the default?
________________________________

**Comment by sdobbs** [comment]
Sure let’s do that

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/make_ReverseForwardFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReverseForwardFit/report_ReverseForwardFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReverseForwardFit

**Pull request merged**
