### PR TITLE
Hdevio async filebuf rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/make_hdevio_async_filebuf_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/make_hdevio_async_filebuf_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/report_hdevio_async_filebuf_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/report_hdevio_async_filebuf_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj

**Comment by faustus123** [comment]
I've modified the code slightly to disable building of this feature on Mac OS X. It failed to build there with the primary complaint being that operator+ was ambiguous between std::streamsize and std::streampos objects. 

I have pulled in changes from master onto this branch and compiled and ran it with the my modifications and the updates from master. It all seemed to work OK.

**Comment by rjones30** [comment]
Hello Dave,

You should be able to add streamsize to streampos and get another
streampos. What is wrong with that?

-Richard

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/make_hdevio_async_filebuf_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/make_hdevio_async_filebuf_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/report_hdevio_async_filebuf_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^hdevio_async_filebuf_rtj/report_hdevio_async_filebuf_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^hdevio_async_filebuf_rtj

**Pull request merged**
