### PR TITLE
add effective cluster radius

### PR DESCRIPTION
**Pull request by igjaegle**
a la A2. it is slightly different than SumV/U.

### CODE REVIEW

**Comment by mashephe** [comment]
This looks very similar to the cluster RMS that that is available as part of the DFCALCluster.  Is it significantly different?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-ecr/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-ecr/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-ecr/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-ecr/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-ecr/make_ijaegle-ecr.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-ecr/make_ijaegle-ecr.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-ecr/report_ijaegle-ecr.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-ecr/report_ijaegle-ecr.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-ecr

**Comment by igjaegle** [comment]
I do not know. The computation is different and this info is not saved in the REST file

**Comment by igjaegle** [comment]
SumU, SumV, & sqrt(SumU**2+SumV**2) are different from ECR

SumU 3.48701 SumV 3.48834 ECR 2.64109 sqrt(SumU**2+SumV**2) 4.93232
SumU 3.51349 SumV 1.56731 ECR 2.25406  sqrt(SumU**2+SumV**2) 3.84722
SumU 5.07155 SumV 0.642781 ECR 2.39047  sqrt(SumU**2+SumV**2) 5.11212

**Comment by mashephe** [comment]
From the printout above it looks like in half of the cases the ECR and RMS are identical?  For reference, the computation of RMS is around lines 210 - 250 of DFCALCluster.cc

I don't necessarily have a problem with the change, but it is generally useful to minimize duplication of code.  I think there is already a fair bit of unused computations in DFCALCluster as it is... much of this is a holdover from legacy RadPhi code that was used as the basis for the GlueX clustering. 

Also note that the U and V referenced in DFCALCluster are different from U and V in DFCALShower.  That set of variables in DFCALShower are the inputs to the neural net that are used to discriminate split offs from low energy showers.  That is why there is a specific set of shower variables available in DFCALShower.  The neural net is run at analysis time.

**Comment by igjaegle** [comment]
As this feature has no apparent discrimination power, I closing this pull request

**Pull request closed without merging**
