### PR TITLE
make use of the proper TOF energy calibration and add to the DTOFPoin…

### PR DESCRIPTION
**Pull request by zihlmann**
…t oject

two more variables, dE1 and dE2 for the energy deposition in the individual planes.
the value dE is the mean of the two.
In addition added two histograms in monitoring_hits for these two variables.

put the f...ing code into the master!

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^TOFEcalib/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^TOFEcalib/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^TOFEcalib/make_TOFEcalib.log](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/make_TOFEcalib.log)
 Build report: [/work/halld/pull_request_test/halld_recon^TOFEcalib/report_TOFEcalib.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/report_TOFEcalib.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^TOFEcalib

**Comment by zihlmann** [comment]
DTOFPpint factory was amended to make sure a TOFPoint has at least one full length paddle and with that at least two TOF hits contributing to a TOFPoint. This was not the case before where even a single TOF hit could make a TOF Point.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^TOFEcalib/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^TOFEcalib/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^TOFEcalib/make_TOFEcalib.log](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/make_TOFEcalib.log)
 Build report: [/work/halld/pull_request_test/halld_recon^TOFEcalib/report_TOFEcalib.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^TOFEcalib/report_TOFEcalib.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^TOFEcalib

**Comment by sdobbs** [comment]
@staylorjlab - did you see any differences with the TOF hit matching?  I would be concerned about how this might change especially near the beamline.

I hope these changes don't get used for the current round of production, out of an abundance of caution (not that I don't believe Beni!)

**Comment by staylorjlab** [comment]
I have not looked at enough events yet to be sure -- I only looked at a handful as a quick check.  I will do a more extensive study.

________________________________

**Pull request merged**
