### PR TITLE
Add a plugin 'TrackingPulls_straight'

### PR DESCRIPTION
**Pull request by keigo-miz**
For Millepede alignment using straight track runs.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^millepede/make_millepede.log](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede/make_millepede.log)
 Build report: [/work/halld/pull_request_test/halld_recon^millepede/report_millepede.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede/report_millepede.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^millepede

**Comment by sdobbs** [comment]
directory collision between this and the previous PR!  
I will try deleting the directory and restarting the tests...

**Comment by keigo-miz** [comment]
Sorry, I already created a new branch & pull-request.
I will close this pull request. Is it OK?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^millepede/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^millepede/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^millepede/make_millepede.log](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede/make_millepede.log)
 Build report: [/work/halld/pull_request_test/halld_recon^millepede/report_millepede.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede/report_millepede.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^millepede

**Comment by sdobbs** [comment]
That's fine with me.

**Pull request closed without merging**
