### PR TITLE
Ecal geometry update v2

### PR DESCRIPTION
**Pull request by staylorjlab**
For the FCAL-II geometry, reads the positions of the lead glass and lead tungstate blocks from the xml specification while maintaining backward compatibility with the old grid-based approach used for FCAL-I.   Inserts ECAL hits along with FCAL hits into the local hit vectors used in the clusterizer codes.   Extrapolates tracks to the face of the insert if it is present.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/make_ECALGeometryUpdateV2.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/make_ECALGeometryUpdateV2.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/report_ECALGeometryUpdateV2.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/report_ECALGeometryUpdateV2.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/make_ECALGeometryUpdateV2.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/make_ECALGeometryUpdateV2.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2/report_ECALGeometryUpdateV2.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ECALGeometryUpdateV2/report_ECALGeometryUpdateV2.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ECALGeometryUpdateV2

**Comment by igjaegle** [comment]
Test the changes for a JEF run (130000) and 2017-01 run period run. It worls fine.

**Comment by igjaegle** [comment]
Simon, do not forget to ask a merge request for halld_sim.

tks ig,

**Pull request merged**
