### PR TITLE
Add plugin and root macro to do CCAL gain calibration using Compton s…

### PR DESCRIPTION
**Pull request by andrsmit**
…cattering events.

### CODE REVIEW

**Comment by igjaegle** [comment]
It looks good.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ccal_compton_gains/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_compton_gains/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ccal_compton_gains/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_compton_gains/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ccal_compton_gains/make_ccal_compton_gains.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_compton_gains/make_ccal_compton_gains.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ccal_compton_gains/report_ccal_compton_gains.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_compton_gains/report_ccal_compton_gains.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ccal_compton_gains

**Review by igjaegle — APPROVED** [review]

**Comment by sdobbs** [comment]
Could you please add the plugin to src/plugins/Calibration/SConscript?  It is currently not being built...

**Comment by andrsmit** [comment]
Do you mean add it to the list of optionally built plugins? I didn't do so to begin with because I assume only a couple people will ever use it.

**Comment by sdobbs** [comment]
This is true for most calibration codes!  =)
The code will probably be used again, so we should verify that it properly
builds

**Comment by igjaegle** [comment]
Hi, Sean, I am testing the procedure now on the new GlueX run with CCAL and
Andrew re-tested it during the last 24hrs on PrimEX runs.

tks ig.

**Comment by sdobbs** [comment]
Sure, the point though is not just testing now, but that the plugin keeps
on getting tested in the future as the codebase changes...

**Comment by igjaegle** [comment]
Sean, most likely, the code will have to be changed as it assumed there is
no B-field.

tks ig.

**Pull request merged**
