### PR TITLE
* commit the changes needed to segegate the HDDM utilities (not

### PR DESCRIPTION
**Pull request by rjones30**
the Gluex hddm i/o libraries, but the tools that build them
  from xml sources) to a separate external package outside of
  the halld_recon tree. [rtj]

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^external_hddm_package_rtj

**Review by rjones30 — COMMENTED** [review]
Notice to build_scripts maintainers: changes to the build environment are needed to complete this PR:
1) install and build https://github.com/Jeffersonlab/HDDM using the std cmake process
2) define HDDM_DIR to point to the install directory created in step 1
3) add $HDDM_DIR/bin to the shell PATH, and verify with "which hddm-cpp"
4) repeat "scons install" in halld_recon/src

**Comment by aaust** [comment]
@rjones30 I think, I have a working version of build_scripts now. The relevant environment variable for the directory will be called HDDM_HOME.

When trying to compile this branch of halld_recon, the following failure appears:
```
[ 98%] PYMODBUILD [.Linux_CentOS7.7-x86_64-gcc4.8.5/libraries/HDDM/setup_hddm_mc_s.py]
[ 98%] PYMODBUILD [.Linux_CentOS7.7-x86_64-gcc4.8.5/libraries/HDDM/setup_hddm_r.py]
scons: *** [.Linux_CentOS7.7-x86_64-gcc4.8.5/libraries/HDDM/hddm_mc_s.so] Error 1
scons: *** [.Linux_CentOS7.7-x86_64-gcc4.8.5/libraries/HDDM/hddm_r.so] Error 1
scons: building terminated because of errors.
```


I also noticed this warning during the compilation of the hddm package:
`Cannot find xalan-j2 at /usr/share/java/xalan-j2.jar, some schema utilities will fail!`
Is it the reason for the problem above?

**Comment by rjones30** [comment]
Alex, you probably need to run scons with SHOWBUILDD=1 to see the real
error. As I recall, the variable needs to be HDDM_DIR, not HDDM_HOME. With
that fix, it should work. Please verify and let me know.
-Richard Jones

**Comment by aaust** [comment]
@rjones30 You are right, it works with HDDM_DIR. I wanted to avoid it because this variable has a different meaning within build_scripts, but I think I found a way around it.

**Comment by rjones30** [comment]
Alex, I just successfully built hdgeant4 inside my container, against G4
binaries distributed under /cvmfs/geant4.cern.ch. It also builds against
ROOT that was rpm-installed in my container. We can talk about it at
Monday's meeting, but what is your thinking on this? Do you want to try to
build G4 from sources yourself on alma9, and then try to link hdgeant4
against that, or are you content to start using the automatic binaries
distributed by the G4 team? It is much easier to upgrade when all that is
required is to change the name of an environment variable.
-Richard Jones

**Comment by aaust** [comment]
This is the relevant build_scripts branch:
https://github.com/JeffersonLab/build_scripts/tree/separate_hddm

I will test some more before switching over

**Review by aaust — APPROVED** [review]
It properly compiles with build_scripts 2.37. I will trigger the automatic build again.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^external_hddm_package_rtj

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^external_hddm_package_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/make_external_hddm_package_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^external_hddm_package_rtj/report_external_hddm_package_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^external_hddm_package_rtj

**Pull request merged**
