### PR TITLE
Get FCAL z position from fcal geometry

### PR DESCRIPTION
**Pull request by staylorjlab**

### CODE REVIEW

**Comment by staylorjlab** [comment]
Please hold off on merging this commit -- I found another issue.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/make_RestoreFCALZ.log](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/make_RestoreFCALZ.log)
 Build report: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/report_RestoreFCALZ.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/report_RestoreFCALZ.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^RestoreFCALZ

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/make_RestoreFCALZ.log](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/make_RestoreFCALZ.log)
 Build report: [/work/halld/pull_request_test/halld_recon^RestoreFCALZ/report_RestoreFCALZ.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^RestoreFCALZ/report_RestoreFCALZ.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^RestoreFCALZ

**Comment by staylorjlab** [comment]
Should be good to go now.

**Pull request merged**
