### PR TITLE
fwmpc and ctof added to hddm

### PR DESCRIPTION
**Pull request by alfab3**
Added FMWPC and CTOF objects to HDDM Event Writer

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log)
 Build report: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer

**Comment by alfab3** [comment]
The header was not properly updated.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log)
 Build report: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log)
 Build report: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log)
 Build report: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/make_alfab_cpp_hddm_writer.log)
 Build report: [/work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^alfab_cpp_hddm_writer/report_alfab_cpp_hddm_writer.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^alfab_cpp_hddm_writer

**Comment by rjones30** [comment]
I see that Albert wanted to add the adc time as a distinct element to the ctof hit structure, which was removed by Simon and made a duplicate of the "t" ctofHit attributed. Does it make sense to have separate times for tdc and adc for the ctof? If the hardware produces them then I see no reason why we cannot add them to the hddm structure. I agree with Simon that you cannot do it the way Albert did, but it can be added if done properly. Let me know what the intention is. -Richard

**Comment by zihlmann** [comment]
I think the TDC timing is not needed because it can not be used in the data anyway. The issue was that the TDC has a dip-switch on the module that was not set correctly during data taking (mea culpa). It used the TDC's internal clock instead of the external clock from the DAQ.

**Review by rjones30 — APPROVED** [review]
Ok, looks good to me. -rtj

**Comment by alfab3** [comment]
Just a quick question before the merge: don't we need the MWPC wire information and CTOF ADC info to properly fold the random triggers into the simulation?

**Comment by rjones30** [comment]
Albert, we do have mwpc wire information:
<fmwpcChamber layer="int" maxOccurs="unbounded" minOccurs="0" wire="int">
      <fmwpcHit dE="float" maxOccurs="unbounded" t="float">
        <fmwpcHitQ q="float" maxOccurs="unbounded"/>
      </fmwpcHit>
</fmwpcTruthHit>

and ctof adc info (as Beni explained there is no working tdc on the ctof,
only time comes from the fadc, as does the dE)
       <ctofCounter bar="int" maxOccurs="unbounded" minOccurs="0">
          <ctofHit end="int" maxOccurs="unbounded" minOccurs="0" dE="float"
t="float"/>
        </ctofCounter>

What are we missing here?
-Richard Jones

**Pull request merged**
