### PR TITLE
add DDIRCLEDRef for SiPM reference time, still requires calibration

### PR DESCRIPTION
**Pull request by jrstevenjlab**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_commissioning_2019

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_commissioning_2019

**Comment by jrstevenjlab** [comment]
The log file says the directory already exists…  Does this mean pull requests can’t have the same branch name as a previous pull request because the auto build will fail?  Or should the previous auto build from this branch be deleted?

**Comment by markito3** [comment]
This is the same thing we had a few days ago. I think that you are 
right; we need to delete the previous build directory. I'll do that and 
retrigger. We need Sean to look at the system when he gets back.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/make_dirc_commissioning_2019.log)
 Build report: [/work/halld/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^dirc_commissioning_2019/report_dirc_commissioning_2019.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^dirc_commissioning_2019

**Pull request merged**
