### PR TITLE
Add CPP non-linear correction

### PR DESCRIPTION
**Pull request by igjaegle**
1/ Ilya's code for the non-linear correction has been copy-paste
2/ 2 tables are added to ccdb

A new monitoring plugins will be also added later in the review process

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-nonlinear/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-nonlinear/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-nonlinear/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-nonlinear/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-nonlinear/make_ijaegle-nonlinear.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-nonlinear/make_ijaegle-nonlinear.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-nonlinear/report_ijaegle-nonlinear.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-nonlinear/report_ijaegle-nonlinear.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-nonlinear

**Comment by sdobbs** [comment]
The suggested implementation looks ok to me.  I guess the next step is waiting for the description of the method?

Side note that I happened to notice - is m_beamSpotX/Y actually used anywhere in the code? A quick review didn't show this.
Might be worth a cleanup later on.

**Comment by igjaegle** [comment]
Message from Ilya:
done comparison,
found the problem in my comparison program,
otherwise looks Ok, i.e. no differences
i.

**Review by aaust — APPROVED** [review]
Looks good. No more custom config files

**Pull request merged**
