### PR TITLE
Fix warnings from fcal pi0 tof mmi

### PR DESCRIPTION
**Pull request by markito3**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/make_fix_warnings_from_FCAL_PI0TOF_MMI.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/make_fix_warnings_from_FCAL_PI0TOF_MMI.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/report_fix_warnings_from_FCAL_PI0TOF_MMI.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/report_fix_warnings_from_FCAL_PI0TOF_MMI.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI

**Comment by markito3** [comment]
I believe that this was caused by a failure in last night's nightly build. Will resubmit the test at some point...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/make_fix_warnings_from_FCAL_PI0TOF_MMI.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/make_fix_warnings_from_FCAL_PI0TOF_MMI.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/report_fix_warnings_from_FCAL_PI0TOF_MMI.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI/report_fix_warnings_from_FCAL_PI0TOF_MMI.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fix_warnings_from_FCAL_PI0TOF_MMI

**Review by aaust — APPROVED** [review]
I approve this message

**Pull request merged**
