### PR TITLE
update ploting script to calculate accidental ration from the random …

### PR DESCRIPTION
**Pull request by zihlmann**
…trigger

data represented by the first plot on the page

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^beamonline/make_beamonline.log](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/make_beamonline.log)
 Build report: [/work/halld/pull_request_test/halld_recon^beamonline/report_beamonline.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/report_beamonline.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^beamonline

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^beamonline/make_beamonline.log](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/make_beamonline.log)
 Build report: [/work/halld/pull_request_test/halld_recon^beamonline/report_beamonline.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/report_beamonline.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^beamonline

**Comment by zihlmann** [comment]
Yes I know, never submit a code you have not tested. mea culpa!

**Comment by zihlmann** [comment]
Hm, I checked the script by running the the plugin over one file and ran the script. not error appeared
and all just worked???

**Comment by markito3** [comment]
should I relaunch the test build?

**Comment by sdobbs** [comment]
I think so

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^beamonline/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^beamonline/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^beamonline/make_beamonline.log](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/make_beamonline.log)
 Build report: [/work/halld/pull_request_test/halld_recon^beamonline/report_beamonline.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^beamonline/report_beamonline.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^beamonline

**Comment by zihlmann** [comment]
does this mean it works now?

**Pull request merged**
