### PR TITLE
Updates to CCAL_online plugin.

### PR DESCRIPTION
**Pull request by andrsmit**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ccal_online/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ccal_online/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ccal_online/make_ccal_online.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/make_ccal_online.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ccal_online/report_ccal_online.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/report_ccal_online.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ccal_online

**Comment by igjaegle** [comment]
The coincidence time window should not be 4.008 ns instead of 6.012 ns?

**Comment by andrsmit** [comment]
I'm doing |t1 - t2| < 6.012, so the total time window is 3*4.008. In other words, I'm including three bunches (the main bunch, and one on either side). I wanted to use a wider time window in case there are tagger modules which have 4ns shifts.

**Comment by zihlmann** [comment]
that does not make any sense. no matter the context. use the prompt peak 
only.
in your way you triple the accidental contribution.

**Comment by andrsmit** [comment]
Okay I can change it to only use the prompt peak. But can I not just subtract accidentals afterwards? I know there is some bunch-to-bunch variation, but shouldn't it be okay just as a monitoring routine?

**Comment by andrsmit** [comment]
Okay, I modified it to only use beam photons in the prompt peak. And I am using one peak on either side for accidental subtraction.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ccal_online/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ccal_online/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ccal_online/make_ccal_online.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/make_ccal_online.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ccal_online/report_ccal_online.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ccal_online/report_ccal_online.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ccal_online

**Comment by zihlmann** [comment]
I am not a programming expert but this is the first time I see the histograms defined in the 
private section of the class. This means these histograms can only be accessed within the class
member functions isn't it?

**Comment by andrsmit** [comment]
Yes, that's right.

**Comment by igjaegle** [comment]
Also, I would suggest filling only histograms
double weight = 0;
if( fabs(brfdt) <  2.004 ) {
 weight = 1.0;
}} else if ( ( -(2.004 + 3.0 * 4.008) <= brfdt && brfdt <= -(2.004 + 4.008) ) ||
                            ( (2.004 + 4.008) <= brfdt && brfdt <= (2.004 + 3.0 * 4.008) ) ) {
                  weight = -0.25;
	        } else {
                  continue;
                }

In this way, you only fill one histo instead of two and simplify the macro afterward. Also do not forget to Sumw2() to have the proper error bar

**Pull request merged**
