### PR TITLE
Detect and fix inconsistent particle types in thrown MC data.

### PR DESCRIPTION
**Pull request by bgrube**
This is intended to fix issue #722.

### CODE REVIEW

**Comment by bgrube** [comment]
For my case, the code solves the issue. But as you mentioned in issue #723 this should be tested on a wider set of data. Are  there any predefined test cases I could run?

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/make_thrownMcParticleTypeMismatch.log](https://halldweb.jlab.org/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/make_thrownMcParticleTypeMismatch.log)
 Build report: [/work/halld/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/report_thrownMcParticleTypeMismatch.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^thrownMcParticleTypeMismatch/report_thrownMcParticleTypeMismatch.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^thrownMcParticleTypeMismatch

**Comment by sdobbs** [comment]
If we test it on the standard b1pi simulations and some bggen that seems
like it would be a good start.

**Comment by bgrube** [comment]
Sorry for not having followed up on this issue.

I ran the b1 pi test analysis at https://github.com/JeffersonLab/hd_utilities/tree/master/b1pi_test. However, it turns out that the reconstruction stage is not exactly reproducible. Running the reconstruction step twice using identical input data from the `mcsmear` step and setting the same random seed results in slightly different DANA REST output files (using `halld_recon` version 4.39.0). The number of entries in some monitoring plots differs on the 10^-4 level. The effect is seen most pronounced in the 3pi invariant mass distribution: [b1pi_standardtest_omegaMass.pdf.diff.pdf](https://github.com/JeffersonLab/halld_recon/files/11205336/b1pi_standardtest_omegaMass.pdf.diff.pdf) Here, the numbers of entries are identical but order of 10 entries out of 1000 have a slightly different 3pi mass (cyan and magenta in the plot).

Running the whole analysis chain using the code from this pull request, I obtain a similar level of (dis)agreement: [b1pi_standardtest_omegaMass.pdf.diff.pdf](https://github.com/JeffersonLab/halld_recon/files/11205355/b1pi_standardtest_omegaMass.pdf.diff.pdf). So, I would consider this test as passed.

Do you have any other tests in mind, that I should try?

**Comment by rjones30** [comment]
Boris,

Yes, this is a long-standing issue. The problem is that it is not a single
issue. When I first studied it back in 2020, I identified 20 or so
different sources of reproducibility in our code. This situation has arisen
because once strict reproducibility was dropped as a requirement for code
validation (or maybe never even tested for), it became (to borrow a concept
from biology) a non-selection feature of the genome. Which means that
random mutations tend to build up in the genes related to this feature. I
very much encourage anyone with time and energy to investigate this and
finish this study. Back when I was working on it, I had the sources of
irreproduciblity down from ~20 to 3. But I never reached zero, so we never
implemented the strict reproducibility check as a requirement for updates.
So the random mutation process continues. My guess is that the sources may
have grown again up from 3 to maybe twice that many by now. That's just a
guess, but history shows that mutations occur if you don't have selection
pressure. My recollection is that the primary sources of
reproducibility are in the combo loops in libraries/Analysis.

-richard jones

**Comment by bgrube** [comment]
Thanks, Richard, for the explanation! Unfortunately, for me it is unclear how to debug this problem efficiently as these events are rather rare and their occurrence is random. I tried using `hd_dump` but could not really make sense of the output, but maybe I was using it wrongly. How did you approach this?

**Comment by rjones30** [comment]
Boris,

I created a special C++ class github.com/rjones30/dilog to help debug this.
The documentation should explain how it works. The tricky thing is that
this needs to find inconsistencies in multithreaded running, which means to
trap differences CLOSE TO WHERE THEY HAPPEN in spite of the fact that
events are being processed out of order. You do have to add a line here and
there to the code and recompile to make it work, but the code runs at full
speed (slowdown is not too much). You can breakpoint the multithreaded
execution in gdb close to where the divergence happens and poke around in
the running thread where the divergence appears. Let me know if the tool
makes sense to you.

-Richard Jones

**Comment by bgrube** [comment]
Thanks a lot, Richard! I'll give it a try.

**Comment by rjones30** [comment]
Boris, my strategy was to first find the spot where the divergence happens
at the Fill call, then start instrumenting loops upstream of that call
related to the construction of the objects that produce the Fill arguments.
This is how I found and fixed the dozen or so problems I have resolved so
far.
-rtj

**Comment by rjones30** [comment]
Boris,

I also have written a utility "rootdiff.py" that recursively compares all
histogram or tprofile objects (not trees) in a directory-structured root
file and reports any differences. Would that tool be useful to you?

-Richard Jones

**Comment by bgrube** [comment]
Yes, this sounds very useful.

**Comment by rjones30** [comment]
Boris, use the link below to grab it. -rtj
https://drive.google.com/file/d/1eKbAZFHMkX4H7IFg6K47n9Mu3Q8NBLVd/view?usp=sharing

**Comment by bgrube** [comment]
Cool! Thanks a lot, Richard!

**Comment by bgrube** [comment]
I agree, you want the combo algorithm basically to behave like a stable sort.

**Review by sdobbs — COMMENTED** [review]
looks good

**Comment by sdobbs** [comment]
It looks like this PR solves the problem it's supposed to - or goes a good way towards doing so.   

The check with MC and reproducibility problems are important to look into, but we want to merge this change in so that it can be used.

I suggest opening an issue that references this PR for further studies.

**Review by sdobbs — APPROVED** [review]
let me actually approve this

**Pull request merged**
