### PR TITLE
Add parameter to ReactionEfficiency plugin that allows user to select a subset of reactions

### PR DESCRIPTION
**Pull request by bgrube**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/make_ReactionEfficiency_Select_Reaction.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction/report_ReactionEfficiency_Select_Reaction.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ReactionEfficiency_Select_Reaction

**Review by jrstevenjlab — APPROVED** [review]
Thanks for adding this to make the plugin more flexible.  I tested it and worked well for adding a couple trees and skipping the rest of the reactions.

**Comment by bgrube** [comment]
Thanks, Justin!

**Pull request merged**
