### PR TITLE
updates for CPP low level hits

### PR DESCRIPTION
**Pull request by sdobbs**
* add handling of writing out all the appropriate fields for FMWPC hits to HDDM event format
* add ability to apply thresholds to both the digit hit amplitude and integral. we can implement the appropriate CCDB table after this

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024

**Comment by aaust** [comment]
I tried to write out events with randomtrigger_skim from a CPP evio file, and I get these entries:
```
      <fmwpcChamber layer="6" wire="77">
          <fmwpcHit dE="0" t="184">
            <fmwpcHitQ q="0" />
            <fmwpcHitQ q="1194" />
            <fmwpcDigiHit amp="0" ped="0" qf="0" />
          </fmwpcHit>
        </fmwpcChamber>
        <fmwpcChamber layer="6" wire="78">
          <fmwpcHit dE="0" t="340.8">
            <fmwpcHitQ q="0" />
            <fmwpcHitQ q="1663" />
            <fmwpcDigiHit amp="0" ped="0" qf="0" />
          </fmwpcHit>
        </fmwpcChamber>

```
For comparison, the master produces this:
```
        <fmwpcChamber layer="6" wire="77">
          <fmwpcHit dE="0" t="184">
          </fmwpcHit>
        </fmwpcChamber>
        <fmwpcChamber layer="6" wire="78">
          <fmwpcHit dE="0" t="340.8">
          </fmwpcHit>
        </fmwpcChamber>
```
Do you understand why HitQ is written out twice, once with 0 value? And why are all digihit entries 0?

**Comment by aaust** [comment]
@sdobbs Did you have any more insights on this?

**Comment by sdobbs** [comment]
Thanks for the reminder on this, I will take a look.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024

**Comment by sdobbs** [comment]
This should be working now - I had some bad function calls in my previous implementation.  

Let me see why the builds aren't even running.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024

**Comment by sdobbs** [comment]
some of it is that we are missing the nightly build...

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024

**Comment by sdobbs** [comment]
ok yeah, my guess is that there is some issues with the disks mounted on the machine where these tests/builds are running

**Comment by aaust** [comment]
You are right, the mapping of the disks was in a weird state. After it was fixed, I redid the nightly build.

**Comment by aaust** [comment]
Reopen to restart test.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024

**Comment by aaust** [comment]
Great, that looks better:
```
      <forwardMWPC>
        <fmwpcChamber layer="4" wire="66">
          <fmwpcHit dE="0" t="476">
            <fmwpcHitQ q="1284" />
            <fmwpcDigiHit amp="179" ped="187" qf="0" />
          </fmwpcHit>
        </fmwpcChamber>
        <fmwpcChamber layer="4" wire="67">
          <fmwpcHit dE="0" t="372">
            <fmwpcHitQ q="1414" />
            <fmwpcDigiHit amp="93" ped="202" qf="0" />
          </fmwpcHit>
        </fmwpcChamber>
      </forwardMWPC>
```

instead of
```
     <forwardMWPC>
        <fmwpcChamber layer="4" wire="66">
          <fmwpcHit dE="0" t="476">
          </fmwpcHit>
        </fmwpcChamber>
        <fmwpcChamber layer="4" wire="67">
          <fmwpcHit dE="0" t="372">
          </fmwpcHit>
        </fmwpcChamber>
      </forwardMWPC>
```

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/make_sdobbs_fmwpc_fix_oct2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024/report_sdobbs_fmwpc_fix_oct2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_fmwpc_fix_oct2024

**Review by aaust — APPROVED** [review]
Tested on CPP evio file.

**Pull request merged**
