### PR TITLE
New root2hdf5 utility rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/make_new_root2hdf5_utility_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/make_new_root2hdf5_utility_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/report_new_root2hdf5_utility_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/report_new_root2hdf5_utility_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj

**Comment by rjones30** [comment]
Hello,

Can someone check that the standard hdf5 library (with includes) is
included in the build environment for halld_recon. It is already a
dependency of hddm, so I am surprised that it is flagged as missing in the
build log.

-Richard Jones

**Comment by rjones30** [comment]
Ok, that change is checked into the PR now. But I would independently like
to ask to initiate the process of getting hdf5-devel added to the standard
jlab build environment, because of the central role that hdf5 plays in
online sharing of big data, as well as community toolkits (eg. keras) for
ML applications.
-Richard Jones

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/make_new_root2hdf5_utility_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/make_new_root2hdf5_utility_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/report_new_root2hdf5_utility_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^new_root2hdf5_utility_rtj/report_new_root2hdf5_utility_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^new_root2hdf5_utility_rtj

**Comment by aaust** [comment]
Ok, thank you. With the CentOS 7 distribution, you would only get hdf5 version 1.8.12, while the current hdf5 release is 1.14.1. We could also install the library locally as its own package with build_scripts, but this would require some development.

**Comment by rjones30** [comment]
Alex, yes. I have ensured that all of my hdf5 development has remained
compatible with 5.1.8 so far, but I regularly test it against a newer
version (5.1.12) to make sure it remains viable going forward.
-Richard Jones

**Pull request merged**
