### PR TITLE
Two track e+ e- raw data skimming with machine learning

### PR DESCRIPTION
**Pull request by acschick**
Adds an optional build plugin in Utilities called epem_ml_skim that selects good two-track e+e- events and writes them to an evio file.

### CODE REVIEW

**Comment by sdobbs** [comment]
One quick comment - this plugin should have a similar SConscript file to other plugins in the repo, not an SConstruct file

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/make_epem_ml_skim.log](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/make_epem_ml_skim.log)
 Build report: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/report_epem_ml_skim.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/report_epem_ml_skim.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^epem_ml_skim

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/make_epem_ml_skim.log](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/make_epem_ml_skim.log)
 Build report: [/work/halld/pull_request_test/halld_recon^epem_ml_skim/report_epem_ml_skim.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^epem_ml_skim/report_epem_ml_skim.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^epem_ml_skim

**Review by aaust — APPROVED** [review]
I got it running with tensorflow on the ifarm (CentrOS7.9), but the compilation requires a more modern gcc (e.g. 8.4.0).
The plugin writes small EVIO skims and has limited monitoring capabilities. Anything more elaborate can be done on top of the evio skims.

**Pull request merged**
