### PR TITLE
Add trd to fit

### PR DESCRIPTION
**Pull request by staylorjlab**
Time-based tracking for the field-on case now can use the TRD and GEM points in the fit.   By default these hits are ignored; their use can be enabled by setting  -PTRKFIT:USE_TRD_HITS=1 -PTRKFIT:USE_GEM_HITS=1 on the command line.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/make_AddTRDtoFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/make_AddTRDtoFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/report_AddTRDtoFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/report_AddTRDtoFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^AddTRDtoFit

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/make_AddTRDtoFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/make_AddTRDtoFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/report_AddTRDtoFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/report_AddTRDtoFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^AddTRDtoFit

**Comment by staylorjlab** [comment]
This failed because I forgot to add one file before requesting a merge -- build check needs to be restarted.

**Comment by sdobbs** [comment]
I restarted the test

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/make_AddTRDtoFit.log](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/make_AddTRDtoFit.log)
 Build report: [/work/halld/pull_request_test/halld_recon^AddTRDtoFit/report_AddTRDtoFit.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^AddTRDtoFit/report_AddTRDtoFit.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^AddTRDtoFit

**Pull request merged**
