### PR TITLE
Comment out unused variable.

### PR DESCRIPTION
**Pull request by markito3**
@jrstevenjlab might want to have a look at this.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^warning-suppression-analysis-library/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^warning-suppression-analysis-library/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^warning-suppression-analysis-library/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^warning-suppression-analysis-library/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^warning-suppression-analysis-library/make_warning-suppression-analysis-library.log](https://halldweb.jlab.org/pull_request_test/halld_recon^warning-suppression-analysis-library/make_warning-suppression-analysis-library.log)
 Build report: [/work/halld/pull_request_test/halld_recon^warning-suppression-analysis-library/report_warning-suppression-analysis-library.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^warning-suppression-analysis-library/report_warning-suppression-analysis-library.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^warning-suppression-analysis-library

**Comment by jrstevenjlab** [comment]
Thanks for the review request Mark.  Prior to this commit by @sdobbs:

https://github.com/JeffersonLab/halld_recon/commit/8423ad42a67683620aca3220161ffcc569219f95#diff-68eb84d13dc9d41ebc2fb68a70181a62

we only included unused showers in the energy sum if they had a detector theta > 2 degrees: 

if(locDetectorTheta < 2.0 || fabs(locDeltaT) > 4.)
    continue;

This requirement was intended to remove spurious showers due to EM background which happened to be in time with the hadronic event of interest.  Do we have a good reason to remove it now?

**Comment by sdobbs** [comment]
Such showers should be removed by the fiducial cuts which are applied at the PreSelect stage.

**Comment by jrstevenjlab** [comment]
Alright, that's probably better if we've defined the these inner blocks in the new fiducial cuts by their contribution from EM background as well as poorly reconstructed showers.  Merging in...

**Pull request merged**
