### PR TITLE
added track probability cut of 10^-3

### PR DESCRIPTION
**Pull request by ilyalarin**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ilarin_060624/make_ilarin_060624.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/make_ilarin_060624.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ilarin_060624/report_ilarin_060624.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/report_ilarin_060624.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ilarin_060624

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^ilarin_060624/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^ilarin_060624/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ilarin_060624/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ilarin_060624/make_ilarin_060624.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/make_ilarin_060624.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ilarin_060624/report_ilarin_060624.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/report_ilarin_060624.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ilarin_060624

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ilarin_060624/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ilarin_060624/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ilarin_060624/make_ilarin_060624.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/make_ilarin_060624.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ilarin_060624/report_ilarin_060624.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ilarin_060624/report_ilarin_060624.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ilarin_060624

**Comment by aaust** [comment]
The nightly-build failed due to ongoing lustre issues.

**Review by aaust — APPROVED** [review]
Thanks, that works.

**Pull request merged**
