### PR TITLE
Reduce dependence on HistogramTools

### PR DESCRIPTION
**Pull request by sdobbs**
We've seen that when using newer versions of gcc and/or ROOT, that sometimes we run into segfaults that seem to be linked to the HistogramTools package.  Also, even though it's convenient, its locking behavior is not the most efficient.  

So this is a first attempt to rewrite plugins to remove the dependence on this header.

I suggest that this PR not be merged until after the next tagged release
I've checked to make sure that the new plugins run correctly, but haven't done more detailed checks - this PR can provide a starting point for those.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools

**Comment by aaust** [comment]
The plugin BCAL_ADC_4ns is not included in the SConscript file, and it does not compile either.
@markdalton Is the plugin still in use, and is it worth fixing?

**Comment by sdobbs** [comment]
For what it's worth, that plugin uses the old-style `DReferenceTrajectory` track extrapolations, which causes the compilation problems.  Also, we haven't had to worry about the 4 ns shifts this plugin corrects for in the past 4 years or so, so it's probably okay to not fix it right now.

**Comment by aaust** [comment]
Ok thanks, I will test all other plugins.

**Comment by aaust** [comment]
- TrackingPulls crashes in the first 30 events
- CDC_Efficiency seems to be stuck in an infinite loop

The remaining list of plugins is running with a similar speed as the master:
- CDC_PerStrawReco
- FDC_Efficiency
- CDC_TimeToDistance
- BCAL_SiPM_saturation
- BCAL_attenlength_gainratio
- FCALLEDTree (needs `-PFCALLED:Tree=1` to run, should be fixed)

The individual histograms still have to be validated.

**Comment by sdobbs** [comment]
Thanks for checking - how did you run these?  Just one plugin at a time?
I tried mostly running all of them together, but these concurrency problems can show up in odd ways.

**Comment by aaust** [comment]
All plugins were run together, but there should not be any interference afaict.
I corrected and validated FDC_Efficiency and TrackingPulls.

**Comment by sdobbs** [comment]
OK, thanks for fixing those.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools

**Comment by aaust** [comment]
This lock is responsible for the "infinite loop". It is opened inside an if statement:
https://github.com/JeffersonLab/halld_recon/blob/94726034b25648ab05e3cce05601478b9c0b95df/src/plugins/monitoring/CDC_Efficiency/JEventProcessor_CDC_Efficiency.cc#L561-L576
but released outside of it:
https://github.com/JeffersonLab/halld_recon/blob/94726034b25648ab05e3cce05601478b9c0b95df/src/plugins/monitoring/CDC_Efficiency/JEventProcessor_CDC_Efficiency.cc#L648

**Comment by sdobbs** [comment]
OK, I pushed a fix for CDC_Efficiency.   I don't think FCALLEDTree needs to be changed - by default it just fills some histograms, so I think it's up to the original author(s) to say if they want the default behavior changed.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools

**Comment by aaust** [comment]
@sdobbs Thanks. I missed that you actually fixed FCALLEDTree in one of your commits.

**Comment by aaust** [comment]
Why is this commented out?
https://github.com/JeffersonLab/halld_recon/blob/fc1a18fa4d6d9bf9704571a437fccdb885770e12/src/plugins/monitoring/CDC_PerStrawReco/JEventProcessor_CDC_PerStrawReco.cc#L503-L532

**Comment by sdobbs** [comment]
That's a mistake which slipped in during debugging some of these other problems - those lines should be uncommented.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/make_sdobbs_remove_histogramtools.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_remove_histogramtools/report_sdobbs_remove_histogramtools.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_remove_histogramtools

**Review by aaust — APPROVED** [review]
Thoroughly tested. The only obvious differences that remain concern histogram types, e.g. TH1I instead of TH1F or similar.

**Pull request merged**
