### PR TITLE
BCAL_online plugin: add option to read out LED triggers in data (defa…

### PR DESCRIPTION
**Pull request by jonzarling**
…ult as before is to skip). Do with command line option BCALONLINE:REQUIRE_PHYSICS_TRIG=0.

### CODE REVIEW

**Comment by jonzarling** [comment]
Clicked through things a little fast, wasn't trying to merge my own pull request... Very minor change though.

**Comment by sdobbs** [comment]
Will let @markito3 give you a good talking to 😉 

I would have thought that you wanted your "&&REQUIRE_PHYSICS_TRIG" check in your new line 533?

**Comment by jonzarling** [comment]
Probably doesn't make a big difference either way, that should give the same result.

**Comment by sdobbs** [comment]
Nevermind, I missed that this requirement was in multiple places, should be fine...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^BCAL_online_options/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^BCAL_online_options/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^BCAL_online_options/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^BCAL_online_options/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^BCAL_online_options/make_BCAL_online_options.log](https://halldweb.jlab.org/pull_request_test/halld_recon^BCAL_online_options/make_BCAL_online_options.log)
 Build report: [/work/halld/pull_request_test/halld_recon^BCAL_online_options/report_BCAL_online_options.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^BCAL_online_options/report_BCAL_online_options.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^BCAL_online_options

**Pull request merged**
