### PR TITLE
Ilya's FCal monitoring plugin for CPP

### PR DESCRIPTION
**Pull request by aaust**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/make_aaust_FCAL_cpp.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/make_aaust_FCAL_cpp.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/report_aaust_FCAL_cpp.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/report_aaust_FCAL_cpp.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/make_aaust_FCAL_cpp.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/make_aaust_FCAL_cpp.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/report_aaust_FCAL_cpp.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/report_aaust_FCAL_cpp.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/make_aaust_FCAL_cpp.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/make_aaust_FCAL_cpp.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp/report_aaust_FCAL_cpp.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_cpp/report_aaust_FCAL_cpp.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_FCAL_cpp

**Comment by aaust** [comment]
The last pull request test was successfully performed with the new nightly-build location on volatile.

**Pull request merged**
