### PR TITLE
Fix hddm library build warnings rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/make_fix_hddm_library_build_warnings_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/make_fix_hddm_library_build_warnings_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/report_fix_hddm_library_build_warnings_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj/report_fix_hddm_library_build_warnings_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fix_hddm_library_build_warnings_rtj

**Review by aaust — COMMENTED** [review]
You changed the length of the arrays from 499 to 500 in May (PR #731).

Can you also look at the build errors, please?
`mv: cannot stat ‘.Linux_CentOS7.7-x86_64-gcc4.8.5/libraries/HDDM/hddm_s.cpp’: No such file or directory`

**Comment by rjones30** [comment]
Alex,

You changed the length of the arrays from 499 to 500 in May (PR #731
> <https://github.com/JeffersonLab/halld_recon/pull/731>).
>

Yes, that was a merge with updates from my external hddm package, that
inadvertently rolled back this fix. I am putting it back in again with this
PR (woops!).

 Can you also look at the build errors, please?

mv: cannot stat
> ‘.Linux_CentOS7.7-x86_64-gcc4.8.5/libraries/HDDM/hddm_s.cpp’: No such file
> or directory


Yes, but I am resolving that in a separate commit, yet to come. That is an
independent issue.
-Richard J.

**Review by aaust — APPROVED** [review]
Great, thank you for the clarification.

**Pull request merged**
