### PR TITLE
Test pull request 

### PR DESCRIPTION
**Pull request by nathalysns**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^src_recon/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src_recon/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^src_recon/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^src_recon/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^src_recon/make_src_recon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^src_recon/make_src_recon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^src_recon/report_src_recon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^src_recon/report_src_recon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^src_recon

**Comment by aaust** [comment]
These scripts do not belong in the halld_recon repository. Can we delete this PR?

**Comment by markdalton** [comment]
It's worth suggesting the best location for these then.  Is it hd_utilities?

**Comment by aaust** [comment]
As far as I can see, these are customized copies of files that are already in hd_utilities: 
https://github.com/JeffersonLab/hd_utilities/tree/master/launch_scripts/launch

In case these copies are of general interest, please write a README description and move them to a folder in hd_utilities.

**Comment by markito3** [comment]
Closing. Intention not clear.

**Pull request closed without merging**
