### PR TITLE
* harden the fadc250 decoding algorithm against a particular kind of

### PR DESCRIPTION
**Pull request by rjones30**
encoding bug characterized by a pulse with zero peak value, followed
  by a long sequence of repeated time words. [rtj]

### CODE REVIEW

**Comment by rjones30** [comment]
Hold off on merging this until I have a chance to fully verify it. This is just a placeholder for the moment.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/make_fix_f250_zero_pulse_encoding_bug_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/make_fix_f250_zero_pulse_encoding_bug_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/report_fix_f250_zero_pulse_encoding_bug_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/report_fix_f250_zero_pulse_encoding_bug_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/make_fix_f250_zero_pulse_encoding_bug_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/make_fix_f250_zero_pulse_encoding_bug_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/report_fix_f250_zero_pulse_encoding_bug_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj/report_fix_f250_zero_pulse_encoding_bug_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fix_f250_zero_pulse_encoding_bug_rtj

**Comment by markito3** [comment]
I'm thinking of including this fix in a new update release of halld_recon. The time scale is a day or so. @rjones30 let me know when you think this is good to go.

**Comment by rjones30** [comment]
Ok, this is good to go now. There is still a fadc125 decoding bug in these input files, but that should be dealt with under a different PR.
-Richard

**Comment by rjones30** [comment]
Mark,

Ok, this PR is good to go now. The revised code now reads successfully
through to the end of the 10 files that Beni reported earlier as crashing
the evio decoder on a fadc250 data format error.

There is still a fadc125 decoding bug in these input files, but that should
be dealt with under a different PR.

-Richard

**Pull request merged**
