### PR TITLE
Implement new scheme to determine if beam was off or on based on coun…

### PR DESCRIPTION
**Pull request by s6pepaul**
…ts in the PS

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/make_change_is_fiducial_method.log](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/make_change_is_fiducial_method.log)
 Build report: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/report_change_is_fiducial_method.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/report_change_is_fiducial_method.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^change_is_fiducial_method

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/make_change_is_fiducial_method.log](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/make_change_is_fiducial_method.log)
 Build report: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/report_change_is_fiducial_method.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/report_change_is_fiducial_method.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^change_is_fiducial_method

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/make_change_is_fiducial_method.log](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/make_change_is_fiducial_method.log)
 Build report: [/work/halld/pull_request_test/halld_recon^change_is_fiducial_method/report_change_is_fiducial_method.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^change_is_fiducial_method/report_change_is_fiducial_method.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^change_is_fiducial_method

**Comment by sdobbs** [comment]
Progress! Either the maintenance yesterday screwed things up or the work
disk is just borked

**Comment by markito3** [comment]
The nightly build used by the tests is for RHEL7. The nightly build for that runs on jlabl5, except that jlabl5 is not longer RHEL7. It is now RHEL8. And the sshd did not accept the ssh key from the node running cron, sandd1.jlab.org, because it was a DSA key. DSA keys appear not to work with the new sshd.

So I am now doing the RHEL7 build on jlabl4. And we will now have a RHEL8 build from jlabl5 going forward.

**Review by sdobbs — APPROVED** [review]
looks good

**Comment by sdobbs** [comment]
Thanks for clearing that up, Mark!

It looks like the only thing that didn't build (yet)? was hdgeant4...
otherwise all the tests work, so I am merging this PR

**Pull request merged**
