### PR TITLE
Apply rootspy compatible modif

### PR DESCRIPTION
**Pull request by igjaegle**
Apply rootspy compatibility modification

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by aaust** [comment]
I tested the plugin on 50k events. Since the histograms are only created whenever they are filled, the macros crash if histograms are not yet present. You can guard against this, for example:
```
if (h_m_gg[i] == NULL)
      continue;
```
This should be do

To avoid interference with other plugins, please store all your histograms in a folder "primex-online"
` Fill1DHistogram("primex-online","histo","h_z", kinfitVertexZ, ";z [cm];Count [a.u.]", 1000, -1000., 1000.);`
instead of
` Fill1DHistogram("histo","","h_z", kinfitVertexZ, ";z [cm];Count [a.u.]", 1000, -1000., 1000.);`

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by igjaegle** [comment]
Corrections are applied and it is compiling w/o error on ifarm

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by sdobbs** [comment]
One other request - could you please not use the Fill1DHistogram() wrappers from HistogramTools.h?  We are in the process of deprecating them.  They often cause problems in the latest version of the code.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/make_ijaegle-primex-eta.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-eta/report_ijaegle-primex-eta.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-eta

**Review by aaust — APPROVED** [review]
It is working fine in the monitoring now.

**Pull request merged**
