### PR TITLE
Correct inconsistencies in the FCAL shower factory

### PR DESCRIPTION
**Pull request by igjaegle**
1/ Add option to remove non-linear correction and decouple it from time correction
FCAL:LOAD_NONLIN_CCDB 0
FCAL:LOAD_TIMING_CCDB 0
2/ Add beam spot x,y
3/ Use for the shower depth correction, the cluster energy instead of the energy corrected

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle_skims

**Comment by mashephe** [comment]
The piece-wise linear/non-linear correction was needed to handle apparently different responses in MC and data.  One may argue it sweeps under the rug a more challenging problem of getting nonlinearities if data and MC to match, but it was necessary.

**Comment by igjaegle** [comment]
NB: 
1/ the linear correction was never applied as Ecutoff (cutoff_energy) is always zero in the DB 
2/ For the gain calculation, the piece-wise linear/non-linear correction must be turn off which was not possible before my correction

**Comment by mashephe** [comment]
Your NB/1 is not correct -- see, for example, version id 94782 of the relevant constant.  It may not be the most recent "mc" variation, but this functionality is needed to preserve backwards compatibility in order to be able to repeat what was done with older MC versions should we desire.  I know your code doesn't not remove the correction, but the comment that it is never applied is not quite correct, and I would recommend removing this comment since it suggests the block of code is irrelevant and can be deleted.

I'm also not sure about the logic concerning the depth correction.  What matters, in principle, when computing the shower depth is the true shower energy, that is the way that it was coded.  The code has now been changed to use the uncorrected cluster energy, which we know is wrong (hence the need for the correction).

**Comment by igjaegle** [comment]
NB/1 no pb if you wish you can remove my comments but the real critical issue is
NB/2 must be addressed ie
the gain calibration must be done without any linear/non-linear energy correction applied
so far it was done with the linear/non-linear energy correction applied and it is also why when finding the new constant for the linear/non-linear energy correction one needed to use the values set in the DB!

**Comment by sdobbs** [comment]
If this change is only needed for the gain calibrations, why don't you just
use the cluster energy and do the depth correction in the gain calibration
plugin?

I wonder if you've done any studies on the effect of using the different
energies on the reconstructed shower quantities?  Aside from which
calculation might be correct, I would be very conservative about making
fundamental changes in our reconstruction code right before a
reconstruction pass without understanding in more detail what is happening.

**Comment by igjaegle** [comment]
The gain calibration is a linear correction and is only valid over some photon energy range. Doing as it is done currently while also applying a non-linear correction is fundamentally wrong. 

Concerning the code change, 
I put back zMax to what it was:
double zMax = FCAL_RADIATION_LENGTH*(FCAL_SHOWER_OFFSET
                                         + log(Egamma/FCAL_CRITICAL_ENERGY));
  
For gain calibration purposes if one sets the option FCAL:LOAD_NONLIN_CCDB 0, Egamma = Eclust.

So the code is not fundamentally changed anymore.

**Comment by igjaegle** [comment]
I wonder if you've done any studies on the effect of using the different
energies on the reconstructed shower quantities? 

I did that a long time ago for the TAPS-wall in Bonn and for FCAL Drew is doing it 
https://userweb.jlab.org/~andrsmit/PrimEx_Meetings/2020/2020_03_27/slides.pdf

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/make_ijaegle_skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle_skims/report_ijaegle_skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle_skims

**Comment by mashephe** [comment]
> The gain calibration is a linear correction and is only valid over some photon energy range. Doing as it is done currently while also applying a non-linear correction is fundamentally wrong.

I would argue the issue is a bit more subtle than this.  As far as I know our algorithm for adjusting gains in a block involves selecting pi0's where one of the photons has most of its energy in the block in question and the other averages over a "good" region of the FCAL.  We then modify the gain for the block in question to put the pi0 peak in the right place.  Then we iterate this process.

The question is:  which energy to use for the photon, the one before or after the nonlinear correction? 

We know the non-linear correction arises from things like attenuation and thresholds and is a  property of the energy of the cluster (and incident photon), not the energy deposition in each block.  And it is has predictable behavior as a function of cluster energy.

So, let's assume you are calibrating two blocks:  one, because of its position far from the beam axis, has a relatively smaller average energy in the pi0 sample than another.  You do this calibration as Igale suggests, before the non-linear correction.  Even if the gain is fundamentally the same in both blocks you will artificially introduce a "gain" factor because they have different non-linear responses and the average energies are different.  In this sense you absorb the non-linear correction into to block gain because the average photon energy depends on block, which is very likely the a true scenario.

The procedure, as coded, is also not without fault.  A similar thing will happen that couples the non-linear correction to the gain factors.  This all arises because we are calibrating using the mass peak which is tied to the energy of a photon.

I don't doubt that both approaches give different answers.  I don't think either is "fundamentally wrong" or right for that matter -- the right one to choose should dependent on an independent metric, like the resolution.

I think the most reasonable solution that attempts to decouple these two things would be to only use photons of a common energy range as the "probe photon" to calibrate the block.  In this case the nonlinearity would be a constant factor across the FCAL and expose the gain variations up to an overall multiplicative constant.  I would advocate that you try to pursue that approach if statistics permits.

The other method may be not to use the pi0 peak.  Years ago we used an algorithm developed by Richard that tries to minimize the pi0 width while making such corrections.  In practice we found this was challenging to implement and sometimes produced instabilities, so it was abandoned in favor of the current technique, which seemed more stable.  It is not obvious this other technique will produce a better answer in a shorter time frame.  Hence I think trying to minimize non-linear effects, not by commenting them out, but by trying to use mono-energetic photons, is a good path to pursue.

**Comment by igjaegle** [comment]
Two things:
1/ With this pull, the default option corresponds to what it is done so far ie non-linear correction is always applied. Only if the user sets  FCAL:LOAD_NONLIN_CCDB 0 in tne config file or in command lne, will the non-linear correction not be applied
2/ In the TAPS-method (which was/is still used in Bonn & Mainz), the gain calibration is applied before the non-linear correction and the non-linear correction is then applied per ring this take care of your example. A caveat to note is that for the non-linear correction as one cannot really select two photons with the same energy so several iterations are also needed for the non-linear correction

**Comment by mashephe** [comment]
I should add that I don't object to making changes that allow one to turn off the nonlinear correction.  (That change can also be made with the existing code that we have always used by using a standalone CCDB file and writing appropriate constants.)  Seems like it would be good to study the entire calibration strategy in light of the comments above, comparing the outcome (not the constants) with what is currently being done, and then decide if such a change is needed before deciding if this change is necessary.

Someone like @sdobbs should comment whether there is a desire/need to preserve backwards compatibility of options.  I suspect this is not an issue, since the default behavior of the code does not change.

**Comment by sdobbs** [comment]
I don't have a problem with adding more options - if I were doing these calibrations, I would also have zeroed them out on the command line rather than just manipulating the CCDB.  However, if you are changing the definition of the command line options, you need to coordinate the changes with whatever scripts are being used for the calibrations and whoever else is using this option (in this case, I guess it's just Colin).

Certainly looking further into ways to potentially improve the energy calibration of the detector is quite interesting.

I'm worried about adding in the beam spot x,y change, without any studies shown about what the effect of the change is.  Note that this technically breaks the covariance matrix lookup table we are using, though I bet this is not a substantial effect.  I don't know how much it matters, since user code will usually make some correction due to the vertex position, particularly if the actual reaction vertex has been determined.

I am pretty sure this change is very small, but Matt probably remembers why I am a little paranoid about making supposedly small changes right before a major production campaign without thorough testing.  Note that standard GlueX reconstruction runs about an order of magnitude or so slower than Primex reconstruction, due to tracking with the magnetic field on.

**Comment by igjaegle** [comment]
Zeroed the value is not working as it is giving Egamma = = Ecluster! It is why I am making this pull request in the first place.

**Comment by mashephe** [comment]
>Zeroed the value is not working as it is giving Egamma = = Ecluster! It is why I am making this pull request in the first place.

I think above you meant to write Egamma = - Ecluster, but anyway... it doesn't matter.  Indeed zeroing the values won't work, you need a better choice.  You can easily get the behavior you desire by:

Ecutoff = 0
C = 2
D = E = 0

I suspect you are already using a custom CCDB table because you probably desire to start with unity gains at the beginning of your gain balancing procedure.  So I would simply write a version of the appropriate constant to this custom table that has the values above, and you can get exactly the behavior you want with the existing code, no problem.

Regarding Sean's comment about the beam spot.  My understanding is this is some sort of average spot for the run, not the event-specific spot.  As long as this value is sane, it must be a very small effect, but I understand Sean's worry about cascading potentially small effects.

As far as photon reconstruction it is important to note that in this class the beam spot is only used to get the angle of the photon correct for the purposes of doing the depth correction.  This class does not use the beam spot to get the four vectors that are ultimately used in high-level analysis.  I suspect the dominant error in this angle reconstruction is not the deviation of the beam spot from zero, but the 2D position resolution of the cluster on the face of the FCAL.

Once the depth correction is done, the output of this class is a position in 3D space (rather than 2D on the plane of the FCAL) that represents the average location of the energy deposition.  In the subsequent algorithms a vector is drawn from this location to the vertex of interest to create a momentum vector.  This is when the vertex enters directly into photon momentum reconstruction.

One should probably dependencies, e.g., like covariance matrix Sean talks about, to be sure there are no secondary issues.

I don't see that these changes make any difference really in the functionality of the code, so I'm not opposed to making them, but for the same reason also don't see why they are necessary.  I had a few other line by line suggestions once I figure out how to use that interface on GitHub....  hmmm.....

**Pull request closed without merging**
