### PR TITLE
added energy and timing plots

### PR DESCRIPTION
**Pull request by alfab3**
Added monitoring plots in FMWPC_online plugin for CTOF and MWPC. Added 2 new root macros for RootSpy for CTOF and FMWPCs timing and energy

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/make_ctof_fmwpc_offmon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/make_ctof_fmwpc_offmon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/report_ctof_fmwpc_offmon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/report_ctof_fmwpc_offmon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon

**Comment by aaust** [comment]
I am recompiling hdgeant4 right now, will resubmit the test once it is done

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/make_ctof_fmwpc_offmon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/make_ctof_fmwpc_offmon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/report_ctof_fmwpc_offmon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/report_ctof_fmwpc_offmon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon

**Comment by aaust** [comment]
sorry, recompiled for the wrong OS

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/make_ctof_fmwpc_offmon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/make_ctof_fmwpc_offmon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon/report_ctof_fmwpc_offmon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ctof_fmwpc_offmon/report_ctof_fmwpc_offmon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ctof_fmwpc_offmon

**Comment by aaust** [comment]
It passed the test, but I get several errors when trying to display some of the plots:

- CTOF_occupancy:
`input_line_52:2:3: error: use of undeclared identifier 'hr_u'
 (hr_u)
  ^
Error in <TRint::HandleTermInput()>: cling::CompilationException caught: Error evaluating expression (hr_u)
`
-  CTOF_energy: `*** Break *** segmentation violation`

**Comment by alfab3** [comment]
Okay I made some changes which I believed caused those errors

**Review by aaust — APPROVED** [review]
useful additions

**Pull request merged**
