### PR TITLE
Write CCAL to hddm. Add disable beam fiducials in random trigger skim

### PR DESCRIPTION
**Pull request by somovalex**
1.  Write CCAL hits to the hddm 
2. Add a flag to disable checking beam fiducial for random trigger skims

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^primex_recon/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex_recon/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^primex_recon/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex_recon/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^primex_recon/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex_recon/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^primex_recon/make_primex_recon.log](https://halldweb.jlab.org/pull_request_test/halld_recon^primex_recon/make_primex_recon.log)
 Build report: [/work/halld/pull_request_test/halld_recon^primex_recon/report_primex_recon.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^primex_recon/report_primex_recon.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^primex_recon

**Comment by sdobbs** [comment]
There is actually no problem with the build tests - I'm working on a few final fixes to the system.

**Comment by somovalex** [comment]
Ok, sounds good
________________________________

**Comment by igjaegle** [comment]
It looks good.

**Pull request merged**
