### PR TITLE
Ijaegle primex skims

### PR DESCRIPTION
**Pull request by igjaegle**
Modified primex eta > 2g & 3pi0 skims

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-skims

**Comment by aaust** [comment]
It did not compile due to mismatched parentheses in JEventProcessor_eta6g_skim.cc:318:56

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-skims

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-skims

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-skims

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-skims

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/make_ijaegle-primex-skims.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ijaegle-primex-skims/report_ijaegle-primex-skims.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ijaegle-primex-skims

**Review by sdobbs — APPROVED** [review]
looks reasonable

**Pull request merged**
