### PR TITLE
Fedora32 rebased

### PR DESCRIPTION
**Pull request by markito3**
Builds under both Python 2 and 3.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/make_fedora32_rebased.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/make_fedora32_rebased.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/report_fedora32_rebased.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/report_fedora32_rebased.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fedora32_rebased

**Comment by markito3** [comment]
So hdgeant.txt says

   timeout: failed to run command 'hdgeant': No such file or directory

but this is supposed to be a test of halld_recon, upon which halld_sim, 
and thus hdgeant, depend. Which leaves me confused...

**Comment by sdobbs** [comment]
It should be based on the nightly build so I’m surprised hdgeant is
missing.

Right now we have the system set up to run the same set of acceptance tests
for each repository. This could of course be changed.

**Comment by markito3** [comment]
hdgeant is there in the nightly build:

[marki@lorentz bin]$ pwd
/scratch/gluex/nightly/2020-07-28/Linux_RHEL7-x86_64-gcc4.8.5/halld_sim/Linux_RHEL7-x86_64-gcc4.8.5/bin
[marki@lorentz bin]$ ls -l hdgeant
-rwxr-xr-x 1 gluex halld-2 451638800 Jul 28 03:41 hdgeant

The environment dump in env^fedora32_rebased shows this

/u/scratch/gluex/nightly/2020-07-28/Linux_RHEL7-x86_64-gcc4.8.5/halld_sim/Linux_RHEL7-x86_64-gcc4.8.5/bin

in the PATH, so that seems right. Which still leaves me confused...

I'm gonna restart the test build...

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/make_fedora32_rebased.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/make_fedora32_rebased.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/report_fedora32_rebased.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/report_fedora32_rebased.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fedora32_rebased

**Comment by markito3** [comment]
Well, at least it's reproducible.

marki@jlab.org, (757)269-5295
________________________________

**Comment by markito3** [comment]
I think that all halld_recon pull requests are doomed to fail as things stand. The test_pull_request.sh script is setting up the environment independently for the run-time tests and I suspect that that is what is causing the problem. I'll submit a dummy pull request...

**Comment by sdobbs** [comment]
Right, if that configuration script isn't setting up a halld_sim, then that
would cause things to fail.

I see two possible solutions:
1) Change how we configure the tests, so that it takes the nightly build
but just overwrites the configuration for halld_recon to be the test build
2) Don't run the hdgeant tests for halld_recon  (not very difficult)

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/make_fedora32_rebased.log](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/make_fedora32_rebased.log)
 Build report: [/work/halld/pull_request_test/halld_recon^fedora32_rebased/report_fedora32_rebased.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^fedora32_rebased/report_fedora32_rebased.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^fedora32_rebased

**Comment by markito3** [comment]
bump...

**Comment by rjones30** [comment]
We have to move forward with this. If there are bugs, they will come out and will be resolved. Python3 is in our lane.
-Richard J.

**Pull request merged**
