### PR TITLE
Add AMPPLOTTER and SQLITECPP_HOME. Cleanup some inconsisted indentation.

### PR DESCRIPTION
**Pull request by markito3**
Restores changes from David's commit 6356cd4 that got lost in the split.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/make_restore_changes_sbms_setenv.py.log](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/make_restore_changes_sbms_setenv.py.log)
 Build report: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/report_restore_changes_sbms_setenv.py.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/report_restore_changes_sbms_setenv.py.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py

**Comment by markito3** [comment]
Looking into removeing AMPLOTTER from this request.

**Comment by markito3** [comment]
Dropped AMPTOOLS sections.

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/make_restore_changes_sbms_setenv.py.log](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/make_restore_changes_sbms_setenv.py.log)
 Build report: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/report_restore_changes_sbms_setenv.py.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/report_restore_changes_sbms_setenv.py.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/make_restore_changes_sbms_setenv.py.log](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/make_restore_changes_sbms_setenv.py.log)
 Build report: [/work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/report_restore_changes_sbms_setenv.py.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^restore_changes_sbms_setenv.py/report_restore_changes_sbms_setenv.py.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^restore_changes_sbms_setenv.py

**Pull request merged**
