### PR TITLE
add TRIG:BYPASS parameter to skip trigger emulation for MC studies su…

### PR DESCRIPTION
**Pull request by jrstevenjlab**
…ch as the particle gun

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/make_MCTrigger_bypass.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/make_MCTrigger_bypass.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/report_MCTrigger_bypass.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/report_MCTrigger_bypass.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MCTrigger_bypass

**Comment by sdobbs** [comment]
Shouldn't you add a return statement inside the BYPASS if-statement?  It looks like this might add two objects of this type into the data stream, when BYPASS=1.

**Comment by jrstevenjlab** [comment]
Yes, thanks for checking.  I pushed a commit with the return statement.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/make_MCTrigger_bypass.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/make_MCTrigger_bypass.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MCTrigger_bypass/report_MCTrigger_bypass.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MCTrigger_bypass/report_MCTrigger_bypass.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MCTrigger_bypass

**Pull request merged**
