### PR TITLE
Ctof digi objects

### PR DESCRIPTION
**Pull request by zihlmann**
Alright, this PR is opened again after adding the necessary code to the DTranslationTable code.
it support CTOF detector Digi objects for ADC and TDC data.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^CTOFDigiObjects/make_CTOFDigiObjects.log](https://halldweb.jlab.org/pull_request_test/halld_recon^CTOFDigiObjects/make_CTOFDigiObjects.log)
 Build report: [/work/halld/pull_request_test/halld_recon^CTOFDigiObjects/report_CTOFDigiObjects.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^CTOFDigiObjects/report_CTOFDigiObjects.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^CTOFDigiObjects

**Comment by jrstevenjlab** [comment]
Looks like this is missing a DCTOFHit_factory, but I see in https://github.com/JeffersonLab/halld_recon/pull/651 this already exists.  So some checking between these two PRs may be useful.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^CTOFDigiObjects/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^CTOFDigiObjects/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^CTOFDigiObjects/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^CTOFDigiObjects/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^CTOFDigiObjects/make_CTOFDigiObjects.log](https://halldweb.jlab.org/pull_request_test/halld_recon^CTOFDigiObjects/make_CTOFDigiObjects.log)
 Build report: [/work/halld/pull_request_test/halld_recon^CTOFDigiObjects/report_CTOFDigiObjects.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^CTOFDigiObjects/report_CTOFDigiObjects.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^CTOFDigiObjects

**Review by aaust — APPROVED** [review]
Both CTOFDigiHits and CTOFTDCDigiHits look reasonable

**Pull request merged**
