### PR TITLE
comment out unused variables

### PR DESCRIPTION
**Pull request by markito3**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^comment_out_unused_variables_MMI/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^comment_out_unused_variables_MMI/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^comment_out_unused_variables_MMI/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^comment_out_unused_variables_MMI/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^comment_out_unused_variables_MMI/make_comment_out_unused_variables_MMI.log](https://halldweb.jlab.org/pull_request_test/halld_recon^comment_out_unused_variables_MMI/make_comment_out_unused_variables_MMI.log)
 Build report: [/work/halld/pull_request_test/halld_recon^comment_out_unused_variables_MMI/report_comment_out_unused_variables_MMI.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^comment_out_unused_variables_MMI/report_comment_out_unused_variables_MMI.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^comment_out_unused_variables_MMI

**Comment by markito3** [comment]
bump

**Review by rjones30 — COMMENTED** [review]
This looks fine to me. -Richard

**Review by rjones30 — APPROVED** [review]
Looks good, rtj

**Pull request merged**
