### PR TITLE
Set REST beam photon energy based on tagger counter

### PR DESCRIPTION
**Pull request by sdobbs**
This fun piece of code sets the energy of DBeamPhoton objects loaded from a REST file based on the counter number, so you can use the latest tagger energy calibration in your analysis.

There are two main cases to consider:
1. If the REST file contains the counter number for each hit, then the selected CCDB context is used to set the beam photon energy, and the saved energy is ignored.  This works in cases where the counter is properly stored, like in recently generated simulations.  (If your simulations don't have the counter info, they are too old and should be regenerated anyway).
2. If the REST file doesn't contain counter number information, then a reverse lookup is performed to figure out the counter number from the stored photon energy, then the latest energy calibration is applied.  This needs to be done to all current reconstructed data, say for an analysis launch.

But how is the reverse lookup properly applied, you may ask?  Practically, you need to specify the CCDB context corresponding to that used to generate the REST file on the command line, e.g. -PREST:JANACALIBCONTEXT="calibtime=2018-05-10-11-05-00"

In principle, this should have been more seamless, since the CCDB context is stored within the REST file.  However, the event containing this and other metadata is not always (or even often!) saved as the first event in the file, so we have to force the issue.  The cause of this misordering is a question for another pull request...

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/make_sdobbs_rest_tagger_en.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/make_sdobbs_rest_tagger_en.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/report_sdobbs_rest_tagger_en.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/report_sdobbs_rest_tagger_en.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en

**Comment by rjones30** [comment]
Sean,

However, the event containing this and other metadata is not always (or
> even often!) saved as the first event in the file, so we have to force the
> issue. The cause of this misordering is a question for another pull
> request...
>

When a hddm input file is opened in JEventSource, to verify it is a valid
hddm I read the first few bytes and then rewind to the beginning of the
stream. I could modify this to read forward to this event containing the
ccdbContext tag and cache that information before rewinding. Would that
make your procedure more robust? I know we have been talking about doing
something about this beam photon energy issue for a long time, so it is
good to see it is happening.

-Richard Jones

**Comment by sdobbs** [comment]
Richard, if we could pull at the CCDB tag like you suggest, that certainly would make the process easier and more convenient (and reduce the number of special cases to worry about).  We probably want to have a search window for a certain number of events, since it's not guaranteed that a file would have this tag.

I also wonder if it's possible in the future to force this data to be written out first.  I wonder if the REST output stream handles flushing to disk?  or is there no way to guarantee the order of events?

**Comment by rjones30** [comment]
Sean,

If you hold the RESTWriter lock and wait until the write call returns, you
will have written to the output stream. No writes that come in after that
can go into the stream ahead of the one that has already been issued.

The REST format is defined such that the ccdb information can be written
into every output event. Is this not being done now?
-Richard

**Comment by sdobbs** [comment]
Richard,
Thanks, I'll try that out.

We're not writing the CCDB info into each event since it's the same for the
whole file - I think this would increase the data size unnecessarily.

---Sean

**Comment by aaust** [comment]
Can't you use the REST:DATAVERSIONSTRING? We could have a lookup table between the recon versions and the calibtime, similar to what we use when we plot the flux from ccdb.

**Comment by sdobbs** [comment]
Well, the CCDB information is in the REST file, so it would be best to
use that if we can propagate it correctly - the data was meant to be
self-documenting in this way.

**Comment by rjones30** [comment]
Sean, maybe by less than 0.5%?
-Richard

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/make_sdobbs_rest_tagger_en.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/make_sdobbs_rest_tagger_en.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en/report_sdobbs_rest_tagger_en.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_rest_tagger_en/report_sdobbs_rest_tagger_en.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_rest_tagger_en

**Review by rjones30 — APPROVED** [review]
Hopefully this reduces the number of false alarms being raised about tagger energies. -Richard

**Pull request merged**
