### PR TITLE
updated DstarZero and DstarPlus masses according to PDG2020

### PR DESCRIPTION
**Pull request by aaust**
thanks to @furletov for discovering the mistake

### CODE REVIEW

**Comment by aaust** [comment]
@gluex No automatic build test?

**Comment by markito3** [comment]
The lack of a test was probably due to the network problems yesterday. The error was "timeout" reported from the GitHub side. I resubmitted the test just now.

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/make_aaust_Dstar_masses.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/make_aaust_Dstar_masses.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/report_aaust_Dstar_masses.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/report_aaust_Dstar_masses.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_Dstar_masses

**Comment by aaust** [comment]
It failed at the hdgeant stage with:
`failed to run command 'hdgeant4': No such file or directory`

**Comment by markito3** [comment]
The nightly build seems to have died quietly last night. I'll clean up and restart...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/make_aaust_Dstar_masses.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/make_aaust_Dstar_masses.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_Dstar_masses/report_aaust_Dstar_masses.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_Dstar_masses/report_aaust_Dstar_masses.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_Dstar_masses

**Review by markito3 — APPROVED** [review]
looks good, agrees with PDG

**Pull request merged**
