### PR TITLE
Bug fix in MilleFieldOn (& Add a helper script)

### PR DESCRIPTION
**Pull request by keigo-miz**
…gnment

Unnecessary sentences in MilleFieldOff are removed.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^millepede_straight/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^millepede_straight/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^millepede_straight/make_millepede_straight.log](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/make_millepede_straight.log)
 Build report: [/work/halld/pull_request_test/halld_recon^millepede_straight/report_millepede_straight.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/report_millepede_straight.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^millepede_straight

**Comment by keigo-miz** [comment]
I added another commit in this branch, in which typos in MilleFieldOn plugin are fixed.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^millepede_straight/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^millepede_straight/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^millepede_straight/make_millepede_straight.log](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/make_millepede_straight.log)
 Build report: [/work/halld/pull_request_test/halld_recon^millepede_straight/report_millepede_straight.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^millepede_straight/report_millepede_straight.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^millepede_straight

**Comment by nsjarvis** [comment]
That is beyond creepy.

**Comment by mikestaib** [comment]
Watching this from the beyond....Glad someone is working on it again.

**Pull request merged**
