### PR TITLE
prevent a crash in DCCALShower_factory, removed debug printout

### PR DESCRIPTION
**Pull request by aaust**
That should guard against the crash described in issue #789 . It does not change the underlying algorithm.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/make_aaust_CCAL_div0.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/make_aaust_CCAL_div0.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/report_aaust_CCAL_div0.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/report_aaust_CCAL_div0.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_CCAL_div0

**Comment by andrsmit** [comment]
Thanks for bringing this to my attention.
I think a more logical place to check if e0!=0 would be after line 2419, when the function 'mom2_ph2t' is called. Actually, it makes more sense to me to rearrange lines 2419-2425 to be written like this:

*********************
e2 = 0.;
x2 = 0.;
y2 = 0.;

if(nadc <= 0) return;

mom2_pht(nadc, ia, id, nzero, iaz, e0, x0, y0, xx, yy, yx);

if(e0 <= 0) return;
*********************

And then on line 2445 where you added the check "if( e0 != 0 && rsq != 0 )", you could either keep it the same or replace it with "if(rsq != 0)" since e0 has already been checked to be greater than 0.

What do you think about this approach instead?

**Comment by staylorjlab** [comment]
The proposal above for reorganization is better.

**Review by andrsmit — APPROVED** [review]
Looks good, thanks.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/make_aaust_CCAL_div0.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/make_aaust_CCAL_div0.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_CCAL_div0/report_aaust_CCAL_div0.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_CCAL_div0/report_aaust_CCAL_div0.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_CCAL_div0

**Comment by aaust** [comment]
In about 1000 remaining monitoring launch jobs, I did not see the failure mode any more so the PR is ready to be merged.

**Pull request merged**
