### PR TITLE
Aaust fcal hits

### PR DESCRIPTION
**Pull request by aaust**
Added FCal hists to REST file as option, can be switched on with `-PREST:WRITE_FCAL_HITS=1`
Also added function to get the FCal hists from a REST file

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_hits/make_aaust_FCAL_hits.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_hits/make_aaust_FCAL_hits.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_hits/report_aaust_FCAL_hits.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_hits/report_aaust_FCAL_hits.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_FCAL_hits

**Comment by aaust** [comment]
Due to the lustre intervention, there was no nightly build to test the PR against. I will repeat the test once the nightly build is in place.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_hits/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_hits/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_hits/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_hits/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_hits/make_aaust_FCAL_hits.log](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_hits/make_aaust_FCAL_hits.log)
 Build report: [/work/halld/pull_request_test/halld_recon^aaust_FCAL_hits/report_aaust_FCAL_hits.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^aaust_FCAL_hits/report_aaust_FCAL_hits.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^aaust_FCAL_hits

**Review by sdobbs — APPROVED** [review]
good addition

**Pull request merged**
