### PR TITLE
* minor fixes to adc/tdc matching [rtj]

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/make_tagm_adc_tdc_matching_fixes_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/make_tagm_adc_tdc_matching_fixes_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/report_tagm_adc_tdc_matching_fixes_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj/report_tagm_adc_tdc_matching_fixes_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tagm_adc_tdc_matching_fixes_rtj

**Comment by sdobbs** [comment]
Hi Richard,

Out of curiosity, what was the underlying problem here?  Were the TDC hits accidentally getting matched with other TDC hits? (am trying to guess from the code changes)

---Sean

**Comment by rjones30** [comment]
Sean,

There was a lack of clarity in the code about what would happen if the adc
and tdc times were not somehow passing all of the checks. This clears up
that ambiguity.

-Richard J.

**Comment by sdobbs** [comment]
OK, thanks!

**Pull request merged**
