### PR TITLE
Add tagger counter info to rest rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/make_add_tagger_counter_info_to_rest_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/make_add_tagger_counter_info_to_rest_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/report_add_tagger_counter_info_to_rest_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/report_add_tagger_counter_info_to_rest_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/make_add_tagger_counter_info_to_rest_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/make_add_tagger_counter_info_to_rest_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/report_add_tagger_counter_info_to_rest_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/report_add_tagger_counter_info_to_rest_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/make_add_tagger_counter_info_to_rest_rtj.log](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/make_add_tagger_counter_info_to_rest_rtj.log)
 Build report: [/work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/report_add_tagger_counter_info_to_rest_rtj.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj/report_add_tagger_counter_info_to_rest_rtj.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^add_tagger_counter_info_to_rest_rtj

**Review by aaust — APPROVED** [review]
I created a REST file with this code, and it showed the additional channel number info. The REST file was readable, both by this branch and the master.

**Pull request merged**
