### PR TITLE
Initial rewrite of HLDetectorTiming plugin

### PR DESCRIPTION
**Pull request by sdobbs**
I rewrote HLDetectorTiming to change the histogramming which was rarely causing weird crashes that were tough to debug, and more importantly made it easier to make histograms for multiple trigger bits, so we can check their performance in parallel.

There's a few other improvements I plan to make here, but want to get this version into production.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/make_sdobbs_hldt_updates_jan2023.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/make_sdobbs_hldt_updates_jan2023.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/report_sdobbs_hldt_updates_jan2023.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/report_sdobbs_hldt_updates_jan2023.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023

**Comment by aaust** [comment]
It crashes almost immediately on the test raw file from 2017:

`hd_root -PPLUGINS=HLDetectorTiming /work/halld/home/aaustreg/hd_rawdata_030300_000.evio`

The stack trace points to 
https://github.com/JeffersonLab/halld_recon/blob/sdobbs_hldt_updates_jan2023/src/plugins/Calibration/HLDetectorTiming/JEventProcessor_HLDetectorTiming.cc#L1304

**Comment by sdobbs** [comment]
The recent commit should fix this problem - I don't see crashes on the few few k events of that file now.  I was testing on 2022 data, so it's funny that this problem didn't show up.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/make_sdobbs_hldt_updates_jan2023.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/make_sdobbs_hldt_updates_jan2023.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/report_sdobbs_hldt_updates_jan2023.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023/report_sdobbs_hldt_updates_jan2023.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_hldt_updates_jan2023

**Review by aaust — APPROVED** [review]
Looks reasonable. Merging in to test on monitoring launch.

**Pull request merged**
