### PR TITLE
First try at simulating trigger energy sums for data

### PR DESCRIPTION
**Pull request by sdobbs**
Initial try at simulating the trigger energy sums for data, mainly for use for comparing to simulation.
Don't take these values too seriously!  But it's better than what was previously implemented.
The code works and should probably sit somewhere that's not just in one of my private branches...

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/make_sdobbs_triggersum_aug2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/make_sdobbs_triggersum_aug2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/report_sdobbs_triggersum_aug2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/report_sdobbs_triggersum_aug2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024

**Comment by sdobbs** [comment]
thanks for catching that, Alex

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/make_sdobbs_triggersum_aug2024.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/make_sdobbs_triggersum_aug2024.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/report_sdobbs_triggersum_aug2024.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_triggersum_aug2024/report_sdobbs_triggersum_aug2024.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_triggersum_aug2024

**Review by aaust — APPROVED** [review]
Useful addition

**Pull request merged**
