### PR TITLE
change code to use gPAMRS as it is inteded to

### PR DESCRIPTION
**Pull request by zihlmann**
make gPARMS great again.

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/make_ST_gPAMRSright.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/make_ST_gPAMRSright.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/report_ST_gPAMRSright.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/report_ST_gPAMRSright.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ST_gPAMRSright

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/make_ST_gPAMRSright.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/make_ST_gPAMRSright.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/report_ST_gPAMRSright.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/report_ST_gPAMRSright.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ST_gPAMRSright

**Comment by zihlmann** [comment]
added code to make sure that the user will be warned in either case of the parameter setting TRKFIT:USE_SC_TIME that this plugin is intended for experts only doing calibration

**Comment by zihlmann** [comment]
pushed the wrong button

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/make_ST_gPAMRSright.log](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/make_ST_gPAMRSright.log)
 Build report: [/work/halld/pull_request_test/halld_recon^ST_gPAMRSright/report_ST_gPAMRSright.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^ST_gPAMRSright/report_ST_gPAMRSright.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^ST_gPAMRSright

**Pull request merged**
