### PR TITLE
added a second map to flag which macro/padnumber should retain its pa…

### PR DESCRIPTION
**Pull request by T-Britton**
…dNumber in the final file name

### CODE REVIEW

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/make_tbritton_dropPadNum.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/make_tbritton_dropPadNum.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/report_tbritton_dropPadNum.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/report_tbritton_dropPadNum.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tbritton_dropPadNum

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/make_tbritton_dropPadNum.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/make_tbritton_dropPadNum.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/report_tbritton_dropPadNum.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/report_tbritton_dropPadNum.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tbritton_dropPadNum

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/make_tbritton_dropPadNum.log](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/make_tbritton_dropPadNum.log)
 Build report: [/work/halld/pull_request_test/halld_recon^tbritton_dropPadNum/report_tbritton_dropPadNum.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^tbritton_dropPadNum/report_tbritton_dropPadNum.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^tbritton_dropPadNum

**Review by faustus123 — APPROVED** [review]
Seems OK.

**Pull request merged**
