### PR TITLE
MLplugin

### PR DESCRIPTION
**Pull request by ReBarsotti**
Adds plugin for use in checking MC/Data agreement in the FCAL machine learning algorithm for shower quality

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by aaust** [comment]
I added the plugin, so that it will be compiled by the test, but the comilation fails:

```
libraries/FCAL/DFCALGeometry.h: In constructor ‘JEventProcessor_Pi0Finder::JEventProcessor_Pi0Finder()’:
libraries/FCAL/DFCALGeometry.h:106:2: error: ‘DFCALGeometry::DFCALGeometry()’ is private
  DFCALGeometry(){};// force use of constructor with arguments.
  ^
In file included from plugins/Utilities/Pi0Finder/JEventProcessor_Pi0Finder.cc:8:0:
plugins/Utilities/Pi0Finder/JEventProcessor_Pi0Finder.h:27:30: error: within this context
   JEventProcessor_Pi0Finder(){}
```

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by mashephe** [comment]
I think this can be fixed by deleting line 42 from JEventProcessor_Pi0Finder.h

The member data that is the FCAL geometry class is not needed by the processor class.

Matt

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by sdobbs** [comment]
@ReBarsotti - I think the system got into a bad state - every time you push changes, it will start another set of automated tests, and these can walk on top of each other.  Please let me know when you're done making changes (I see that there's a conflict in your current branch), and we can clear some directories and restart the test if needed.

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by gluex** [comment]
Build status for this pull request: FAILURE
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by sdobbs** [comment]
OK, the tests stalled because one of the required files was missing again... I need to check with @markito3 to see how to stop this from happening...

Anyway, I restarted the machinery and I think that this time the build tests will pass.  Note that the conflict with src/plugins/Utilities/SConscript needs to be resolved before this PR can be merged.  You can try pulling the master branch into your branch to start the process of resolving this conflict.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^MLplugin/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^MLplugin/make_MLplugin.log](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/make_MLplugin.log)
 Build report: [/work/halld/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^MLplugin/report_MLplugin.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^MLplugin

**Review by sdobbs — APPROVED** [review]
Looks fine, let's merge this in

**Pull request merged**
