### PR TITLE
hd_rsai_gen

### PR DESCRIPTION
**Pull request by faustus123**
Utility to help generate images for training Hydra models.

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/make_davidl_hd_rsai_gen.log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/make_davidl_hd_rsai_gen.log)
 Build report: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/report_davidl_hd_rsai_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/report_davidl_hd_rsai_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen

**Comment by sdobbs** [comment]
will kick off the tests again, maybe the system was tired on Sunday

**Comment by gluex** [comment]
Test status for this pull request: FAILURE
 
 Failures: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/failures.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-failures.txt)
 Summary: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/make_davidl_hd_rsai_gen.log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/make_davidl_hd_rsai_gen.log)
 Build report: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/report_davidl_hd_rsai_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/report_davidl_hd_rsai_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen

**Comment by sdobbs** [comment]
tests should work now, already restarted them for this PR...

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/make_davidl_hd_rsai_gen.log](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/make_davidl_hd_rsai_gen.log)
 Build report: [/work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen/report_davidl_hd_rsai_gen.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^davidl_hd_rsai_gen/report_davidl_hd_rsai_gen.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^davidl_hd_rsai_gen

**Pull request merged**
