### PR TITLE
handle fADC125 emulation on pure raw data based on the TTab

### PR DESCRIPTION
**Pull request by sdobbs**
As suggested by @faustus123 - this should resolve issue #643

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/make_sdobbs_f125_ttab.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/make_sdobbs_f125_ttab.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/report_sdobbs_f125_ttab.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/report_sdobbs_f125_ttab.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab

**Comment by nsjarvis** [comment]
Could we change the default so that the emulation is switched off unless explicitly requested?

All the f125 readout modes include the pulse data.   There is no readout mode for raw data only.

**Comment by sdobbs** [comment]
does it hurt to run the emulation?  it doesn't overwrite the pulse data, it just saves the information for comparison

that said, I don't particularly care, changing the default is pretty trivial

**Comment by nsjarvis** [comment]
Wastes resources if the user doesn't want the output.

If it is run by default then the code has to be updated for each new detector using the f125, it causes confusion until that is done.

**Comment by sdobbs** [comment]
in the current implementation, if a new detector that has not been implemented is encountered, then the emulation isn't run so there's no worry about confusion.  the code should be updated for new detectors, though.

as for the resource concern, I don't have an objection to disabling the simulations by default but would like wider buy-in before making the change

**Comment by sdobbs** [comment]
No one complained at the software meeting, so I pushed @nsjarvis 's requested change.

Maybe no one cares about the fADC250 emulation and we should disable it by default as well.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/make_sdobbs_f125_ttab.log](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/make_sdobbs_f125_ttab.log)
 Build report: [/work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab/report_sdobbs_f125_ttab.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^sdobbs_f125_ttab/report_sdobbs_f125_ttab.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^sdobbs_f125_ttab

**Review by nsjarvis — APPROVED** [review]
Nice fix, thanks.  

I do think it would be sensible to make both fadc emulators run by request (not default) as they are used by only a few people, for debugging and trying out new fadc configurations.  I would check w the f250 experts before changing their default.

**Pull request merged**
