### PR TITLE
adding plugin dedx_tree, makes tree of CDC track angle, momentum, dEdx

### PR DESCRIPTION
**Pull request by nsjarvis**
This is the plugin that I used to generate the trees for CDC dE/dx corrections (and also to draw a more finely-grained dE/dx histogram).

### CODE REVIEW

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/make_nsj_dedx_tree.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/make_nsj_dedx_tree.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/report_nsj_dedx_tree.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/report_nsj_dedx_tree.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_dedx_tree

**Comment by aaust** [comment]
Please add the plugin to the SConscript file in the folder above, so that it will be compiled in the automatic test:

https://github.com/JeffersonLab/halld_recon/blob/master/src/plugins/Utilities/SConscript

**Comment by nsjarvis** [comment]
Is it ok to add it to the optional build section?

**Comment by nsjarvis** [comment]
I added it to the regular build-every-time group.

**Comment by gluex** [comment]
Test status for this pull request: SUCCESS
 
  Summary: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/tests/summary.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/tests-summary.txt)
 Logs: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/tests/log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/tests-logs)
 
 Build log: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/make_nsj_dedx_tree.log](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/make_nsj_dedx_tree.log)
 Build report: [/work/halld/pull_request_test/halld_recon^nsj_dedx_tree/report_nsj_dedx_tree.txt](https://halldweb.jlab.org/pull_request_test/halld_recon^nsj_dedx_tree/report_nsj_dedx_tree.txt)
 Location of build: /work/halld/pull_request_test/halld_recon^nsj_dedx_tree

**Review by aaust — APPROVED** [review]
It compiles. I did not test the plugin itself.

**Pull request merged**
